spring:
  datasource:
    url: jdbc:mysql://${DBHOST}:${DBPORT}/${DBNAME}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL}
    username: ${DBUSER}
    password: ${DBPASSWORD}
  flyway:
    password: ${DBPASSWORD}
    schemas: ${DBNAME}
    locations: classpath:db/migration/common,classpath:db/migration/tenant/hee,classpath:db/migration/stage

logging:
  file: ${LOG_DIR}/reference.log
