# ===================================================================
# Northern Ireland Medical & Dental Training Agency config.
#
# This file contains overrides for NIMDTA specific values,
# ===================================================================
flyway:
  locations: classpath:db/migration/common,classpath:db/migration/tenant/nimdta
