SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `Site`
DROP CONSTRAINT `CONSTRAINT_26D7`;

ALTER TABLE `Site`
DROP PRIMARY KEY;


ALTER TABLE `Site`
ADD COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `Site` ADD PRIMARY KEY(id);

ALTER TABLE `Site`
MODIFY `siteCode` VARCHAR(255);

--make trust code nullable
ALTER TABLE `Site`
MODIFY `trustCode` VARCHAR(255);

ALTER TABLE `Site`
ADD COLUMN `trustId` bigint(20);

---

ALTER TABLE `Trust`
DROP CONSTRAINT `CONSTRAINT_4C6`;

ALTER TABLE `Trust`
DROP PRIMARY KEY;

ALTER TABLE `Trust`
ADD COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `Trust` ADD PRIMARY KEY(id);

ALTER TABLE `Trust`
MODIFY `code` VARCHAR(255);

---

ALTER TABLE `Grade`
DROP CONSTRAINT `CONSTRAINT_40`;

ALTER TABLE `Grade`
DROP PRIMARY KEY;

ALTER TABLE `Grade`
ADD COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `Grade` ADD PRIMARY KEY(id);

ALTER TABLE `Grade`
MODIFY `abbreviation` VARCHAR(255);

ALTER TABLE `Grade`
ADD COLUMN `intrepidId` VARCHAR(255);

---

--remove unique constraint on code
ALTER TABLE `MedicalSchool`
DROP CONSTRAINT `CONSTRAINT_79D`;

ALTER TABLE `MedicalSchool`
ALTER COLUMN `code` VARCHAR(255);

SET FOREIGN_KEY_CHECKS = 1;