TRUNCATE TABLE Role;

INSERT INTO Role (code,label,status) VALUES('Academic Supervisor','Academic Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Academic Tutor','Academic Tutor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('AccreditationPathway.Administrator','AccreditationPathway.Administrator','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Activity Supervisor (Public Health)','Activity Supervisor (Public Health)','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Administrator.HelperFunctions','Administrator.HelperFunctions','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Administrator.HelpFunctions','Administrator.HelpFunctions','CURRENT');
INSERT INTO Role (code,label,status) VALUES('ARCP External Member','ARCP External Member','CURRENT');
INSERT INTO Role (code,label,status) VALUES('ARCP Lay Member','ARCP Lay Member','CURRENT');
INSERT INTO Role (code,label,status) VALUES('ARCP/Recruitment Assessor','ARCP/Recruitment Assessor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('ARCP/RITA Panel Member','ARCP/RITA Panel Member','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Assessment Panel Member','Assessment Panel Member','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Assessment.Access','Assessment.Access','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Assessment.AddNew','Assessment.AddNew','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Assessment.Batch','Assessment.Batch','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Assessment.FormR.SuperUser','Assessment.FormR.SuperUser','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Assessment.FormRSignoff','Assessment.FormRSignoff','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Assessment.PanelMember','Assessment.PanelMember','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Clinical Supervisor','Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Consultant','Consultant','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Course Facilitator','Course Facilitator','CURRENT');
INSERT INTO Role (code,label,status) VALUES('CPPS.NonAdministrator.CaseManager','CPPS.NonAdministrator.CaseManager','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Dental Clinical Supervisor','Dental Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Dental Educational Supervisor','Dental Educational Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Dental Trainer','Dental Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Dentist in Training','Dentist in Training','CURRENT');
INSERT INTO Role (code,label,status) VALUES('DR in Training','DR in Training','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Dummy Record','Dummy Record','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Educational Supervisor','Educational Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('EMD.Self Service','EMD.Self Service','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Foundation Clinical Supervisor','Foundation Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Foundation Educational Supervisor','Foundation Educational Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Foundation Trainer','Foundation Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Adviser/Associate','GP Adviser/Associate','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Advisor/Associate','GP Advisor/Associate','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Appraiser','GP Appraiser','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Associate Director','GP Associate Director','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Associate Trainer','GP Associate Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Clinical Supervisor','GP Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Educational Supervisor','GP Educational Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Foundation Clinical Supervisor','GP Foundation Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Foundation Trainer','GP Foundation Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Out of Hours Clinical Supervisor','GP Out of Hours Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Out of Hours Supervisor','GP Out of Hours Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Practice Manager','GP Practice Manager','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Prospective trainer','GP Prospective trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Supervisor trainer','GP Supervisor trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Trainer','GP Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Trainer group convener','GP Trainer group convener','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Trainer Workshop Convenor','GP Trainer Workshop Convenor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Training Programme Director','GP Training Programme Director','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP Tutor','GP Tutor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('GP V9 Person Upload','GP V9 Person Upload','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Head of School','Head of School','CURRENT');
INSERT INTO Role (code,label,status) VALUES('HEEWM Clinical Supervisor','HEEWM Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('HEEWM Dental Clinical Supervisor','HEEWM Dental Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('HEEWM Dental Educational Supervisor','HEEWM Dental Educational Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('HEEWM Educational Supervisor','HEEWM Educational Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('HEEWM GP Clinical Supervisor','HEEWM GP Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('HEEWM GP Educational Supervisor','HEEWM GP Educational Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('HEEWM GP Foundation Trainer','HEEWM GP Foundation Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('HEEWM GP Practice Manager','HEEWM GP Practice Manager','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Induction zzz Refresher Supervisor','Induction zzz Refresher Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Leave.Administrator.Manual','Leave.Administrator.Manual','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Leave.Approver.Administrator','Leave.Approver.Administrator','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Leave.Approver.NonAdministrator','Leave.Approver.NonAdministrator','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Leave.HelperFunctions','Leave.HelperFunctions','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Local Office Role','Local Office Role','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Medical Director','Medical Director','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Medical Education Managers','Medical Education Managers','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Advisor/Associate','NE.Advisor/Associate','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.ARCP Panel Chair','NE.ARCP Panel Chair','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Associate Director','NE.Associate Director','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Foundation Trainer','NE.Foundation Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.GP Appraiser','NE.GP Appraiser','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.GP Tutor','NE.GP Tutor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Head of School','NE.Head of School','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Intending Trainer','NE.Intending Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Lead TPD','NE.Lead TPD','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Out of Hours Supervisor','NE.Out of Hours Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Prospective trainer','NE.Prospective trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Responsible Officer','NE.Responsible Officer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Retainer','NE.Retainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Supervisor trainer','NE.Supervisor trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.TPD','NE.TPD','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Trainer','NE.Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Training Programme Director','NE.Training Programme Director','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NE.Trust Dr','NE.Trust Dr','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NonAdministrator.HelperFunction','NonAdministrator.HelperFunction','CURRENT');
INSERT INTO Role (code,label,status) VALUES('NonAdministrator.HelperFunctions','NonAdministrator.HelperFunctions','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Non-Trainee Doctor','Non-Trainee Doctor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('OOH Supervisor','OOH Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Person.Access','Person.Access','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Person.AddNew','Person.AddNew','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Placeholder','Placeholder','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Placement Manager Planner','Placement Manager Planner','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Placement Manager Read Only','Placement Manager Read Only','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Post.Access','Post.Access','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Practice Manager','Practice Manager','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Programme Director','Programme Director','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Programme.Access','Programme.Access','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Prospective Trainer','Prospective Trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Responsible Officer','Responsible Officer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Retained Doctor','Retained Doctor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Retained Doctor Supervisor','Retained Doctor Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SAS Doctor','SAS Doctor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.Accreditation','SelfService.Accreditation','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.Confidential','SelfService.Confidential','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.ContactDetails','SelfService.ContactDetails','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.CPPS','SelfService.CPPS','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.Documents','SelfService.Documents','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.FormR','SelfService.FormR','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.LeaveApplicant','SelfService.LeaveApplicant','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.Questionnaire','SelfService.Questionnaire','CURRENT');
INSERT INTO Role (code,label,status) VALUES('SelfService.TrainingHistory','SelfService.TrainingHistory','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Simulation Educator','Simulation Educator','CURRENT');
INSERT INTO Role (code,label,status) VALUES('STC Chairman','STC Chairman','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Supervising Consultant','Supervising Consultant','CURRENT');
INSERT INTO Role (code,label,status) VALUES('TeachingSessions.Admin','TeachingSessions.Admin','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Training Programme Director','Training Programme Director','CURRENT');
INSERT INTO Role (code,label,status) VALUES('Trust Doctor','Trust Doctor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Clinical Supervisors Bath','V9 Clinical Supervisors Bath','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors 2gether','V9 Educational Supervisors 2gether','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors AWP','V9 Educational Supervisors AWP','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors BANES PCT','V9 Educational Supervisors BANES PCT','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors Bath','V9 Educational Supervisors Bath','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors Gloucester','V9 Educational Supervisors Gloucester','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors North Bristol','V9 Educational Supervisors North Bristol','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors Public Health','V9 Educational Supervisors Public Health','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors RNHRD','V9 Educational Supervisors RNHRD','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors Sirona','V9 Educational Supervisors Sirona','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors SomPar','V9 Educational Supervisors SomPar','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors St Peter''s','V9 Educational Supervisors St Peter''s','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors Swindon','V9 Educational Supervisors Swindon','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors Taunton','V9 Educational Supervisors Taunton','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors UHB','V9 Educational Supervisors UHB','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors Weston','V9 Educational Supervisors Weston','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Educational Supervisors Yeovil','V9 Educational Supervisors Yeovil','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 Training Programme Directors','V9 Training Programme Directors','CURRENT');
INSERT INTO Role (code,label,status) VALUES('V9 University of Bristol','V9 University of Bristol','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Adviser / Associate','v9GP Adviser / Associate','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Assessor','v9GP Assessor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Course organiser','v9GP Course organiser','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP ETR','v9GP ETR','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP FCS','v9GP FCS','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP GP tutor','v9GP GP tutor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Leader','v9GP Leader','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Non principal','v9GP Non principal','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP OOH supervisor','v9GP OOH supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Practice manager','v9GP Practice manager','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Prospective retainee','v9GP Prospective retainee','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Prospective trainer','v9GP Prospective trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Retainer','v9GP Retainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Scheme organiser','v9GP Scheme organiser','CURRENT');
INSERT INTO Role (code,label,status) VALUES('v9GP Supervisor trainer','v9GP Supervisor trainer','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Accreditation Pathway','YH Accreditation Pathway','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Add Person','YH Add Person','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Assessment.General','YH Assessment.General','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Clinical Supervisor','YH Clinical Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Data.DataAnalysisTools','YH Data.DataAnalysisTools','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Data.LicenceManager','YH Data.LicenceManager','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Data.User','YH Data.User','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Education','YH Education','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Educational Supervisor','YH Educational Supervisor','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Placeholder','YH Placeholder','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Programme.Support','YH Programme.Support','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Quality','YH Quality','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Strategic.Workforce.Planning','YH Strategic.Workforce.Planning','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Testing.CPPS','YH Testing.CPPS','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Training Programme Director','YH Training Programme Director','CURRENT');
INSERT INTO Role (code,label,status) VALUES('YH Trust.Admin','YH Trust.Admin','CURRENT');
