CREATE TABLE `QualificationReference` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code` varchar(255) NOT NULL,
  `label` varchar(255) NOT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `QualificationReference` (code,label,status)
VALUES ('(ABIM)American Board Int Med','(ABIM)American Board Int Med','CURRENT'),
('1st Yr Fac of Biology (Madrid)','1st Yr Fac of Biology (Madrid)','CURRENT'),
('3rd medical state exam','3rd medical state exam','CURRENT'),
('9MB Chb','9MB Chb','CURRENT'),
('ABA','ABA','CURRENT'),
('Academic Degree in Medicine','Academic Degree in Medicine','CURRENT'),
('Academic Medical Training','Academic Medical Training','CURRENT'),
('AFRCS (Part 1)','AFRCS (Part 1)','CURRENT'),
('AKC','AKC','CURRENT'),
('AKC - Association of King''s College','AKC - Association of King''s College','CURRENT'),
('ALLS','ALLS','CURRENT'),
('AM','AM','CURRENT'),
('AMC','AMC','CURRENT'),
('Artsexamen','Artsexamen','CURRENT'),
('Arts-Examen medical, The Nethe','Arts-Examen medical, The Nethe','CURRENT'),
('Associate Member of RCGP','Associate Member of RCGP','CURRENT'),
('B ChD','B ChD','CURRENT'),
('B Dent Sc','B Dent Sc','CURRENT'),
('B Med','B Med','CURRENT'),
('B Med and Surgery','B Med and Surgery','CURRENT'),
('B Med Sci   BM  BS  MRCGP','B Med Sci   BM  BS  MRCGP','CURRENT'),
('B Med Sci (Hons)','B Med Sci (Hons)','CURRENT'),
('B Med SciI','B Med SciI','CURRENT'),
('B MedSci','B MedSci','CURRENT'),
('B Ms','B Ms','CURRENT'),
('B Soc Science (Psychology)','B Soc Science (Psychology)','CURRENT'),
('B.D.S','B.D.S','CURRENT'),
('B.D.S degree in dentistry','B.D.S degree in dentistry','CURRENT'),
('B.Dent.Sc','B.Dent.Sc','CURRENT'),
('B.Med Sci BM BS DCH MRCGP','B.Med Sci BM BS DCH MRCGP','CURRENT'),
('B.Med.Sc','B.Med.Sc','CURRENT'),
('B.MED.SCI, BM, BS, MRCP, DTM&H','B.MED.SCI, BM, BS, MRCP, DTM&H','CURRENT'),
('B.Sc (Med Sci), MBChB','B.Sc (Med Sci), MBChB','CURRENT'),
('B.Sc. Psychology','B.Sc. Psychology','CURRENT'),
('BA ( HONS) French with Management Studies','BA ( HONS) French with Management Studies','CURRENT'),
('BA (Hons)','BA (Hons)','CURRENT'),
('BA (hons) Graphic Arts and Design','BA (hons) Graphic Arts and Design','CURRENT'),
('BA (Hons) History and French','BA (Hons) History and French','CURRENT'),
('BA (Hons) in Urban Planning','BA (Hons) in Urban Planning','CURRENT'),
('BA (Hons) Music','BA (Hons) Music','CURRENT'),
('BA (Hons) Natural Sciences ','BA (Hons) Natural Sciences ','CURRENT'),
('BA (Hons) Psychology','BA (Hons) Psychology','CURRENT'),
('BA (Joint Hons) Philosophy & Politics','BA (Joint Hons) Philosophy & Politics','CURRENT'),
('BA Anthropology','BA Anthropology','CURRENT'),
('BA Classics','BA Classics','CURRENT'),
('BA History (Hons)','BA History (Hons)','CURRENT'),
('BA Hons (Oxon)','BA Hons (Oxon)','CURRENT'),
('BA MBBS MRCGP','BA MBBS MRCGP','CURRENT'),
('BA Med Sci, BMBCL, DRCOG, MRCG','BA Med Sci, BMBCL, DRCOG, MRCG','CURRENT'),
('BA SCI','BA SCI','CURRENT'),
('BA Social Anthropology','BA Social Anthropology','CURRENT'),
('BA Zoology','BA Zoology','CURRENT'),
('BA(Hons) Politics & International Relations','BA(Hons) Politics & International Relations','CURRENT'),
('BA, BM, BCh','BA, BM, BCh','CURRENT'),
('BA. B. Dent. Sc. ','BA. B. Dent. Sc. ','CURRENT'),
('BACH MED','BACH MED','CURRENT'),
('Bachelor','Bachelor','CURRENT'),
('Bachelor of Arts','Bachelor of Arts','CURRENT'),
('Bachelor of Arts and Medicine','Bachelor of Arts and Medicine','CURRENT'),
('Bachelor of Dental Science (BDSc or BDentSc)','Bachelor of Dental Science (BDSc or BDentSc)','CURRENT'),
('Bachelor of Dental Surgery','Bachelor of Dental Surgery','CURRENT'),
('Bachelor of Dental Surgery (BDS or BChD or BDentS)','Bachelor of Dental Surgery (BDS or BChD or BDentS)','CURRENT'),
('Bachelor of Dental Surgery (BDS)','Bachelor of Dental Surgery (BDS)','CURRENT'),
('Bachelor of Dental Surgery (Hons)','Bachelor of Dental Surgery (Hons)','CURRENT'),
('Bachelor of Dentistry (BDent)','Bachelor of Dentistry (BDent)','CURRENT'),
('Bachelor of Medical Sciences','Bachelor of Medical Sciences','CURRENT'),
('Bachelor of Medicine and ...','Bachelor of Medicine and ...','CURRENT'),
('Bachelor of Medicine and Surgery, MBChB','Bachelor of Medicine and Surgery, MBChB','CURRENT'),
('Bachelor of Medicine, Bachelor of Surgery; MBChB','Bachelor of Medicine, Bachelor of Surgery; MBChB','CURRENT'),
('Bachelor of Medicine, Batchelor of Surgery MBChB','Bachelor of Medicine, Batchelor of Surgery MBChB','CURRENT'),
('Bachelor of Medine & Surgery','Bachelor of Medine & Surgery','CURRENT'),
('Bachelor of Oral Health in Dental Science (B OH DS','Bachelor of Oral Health in Dental Science (B OH DS','CURRENT'),
('Bachelor of Psychology','Bachelor of Psychology','CURRENT'),
('Bachelor of Science (Honours)','Bachelor of Science (Honours)','CURRENT'),
('Bachelor of Science with Honours - Pharmacology','Bachelor of Science with Honours - Pharmacology','CURRENT'),
('Bachelor of Science with Honours Human Biology','Bachelor of Science with Honours Human Biology','CURRENT'),
('Bachelor of Surgery','Bachelor of Surgery','CURRENT'),
('BARTS & BATLS (ATLS)','BARTS & BATLS (ATLS)','CURRENT'),
('Basic Surgical Skills','Basic Surgical Skills','CURRENT'),
('Batchelor in Dental Sciences','Batchelor in Dental Sciences','CURRENT'),
('BC BCh Bachelor of Surgery','BC BCh Bachelor of Surgery','CURRENT'),
('BC, BCh Bachelor of Surgery','BC, BCh Bachelor of Surgery','CURRENT'),
('Bch MED','Bch MED','CURRENT'),
('BChB','BChB','CURRENT'),
('BChD (Dental)','BChD (Dental)','CURRENT'),
('BChD Bachelor of Dental Surgery','BChD Bachelor of Dental Surgery','CURRENT'),
('Bchir','Bchir','CURRENT'),
('BChir Bachelor of Surgery','BChir Bachelor of Surgery','CURRENT'),
('BChir MB','BChir MB','CURRENT'),
('BChir, MB','BChir, MB','CURRENT'),
('Bcs (Hons) Biology','Bcs (Hons) Biology','CURRENT'),
('BDentSci','BDentSci','CURRENT'),
('BDMS','BDMS','CURRENT'),
('BDS','BDS','CURRENT'),
('BDS (Hons)','BDS (Hons)','CURRENT'),
('BDS Bachelor Dental Surgery','BDS Bachelor Dental Surgery','CURRENT'),
('BDS Bachelor of Dental Surgery','BDS Bachelor of Dental Surgery','CURRENT'),
('BDS Dentistry ','BDS Dentistry ','CURRENT'),
('BDS NUI','BDS NUI','CURRENT'),
('BDS VU','BDS VU','CURRENT'),
('BDSBrist','BDSBrist','CURRENT'),
('BDSc','BDSc','CURRENT'),
('BDSLond','BDSLond','CURRENT'),
('BDSManc','BDSManc','CURRENT'),
('BELGIAN MEDICAL DEGREE','BELGIAN MEDICAL DEGREE','CURRENT'),
('BHB','BHB','CURRENT'),
('BIOCHEMISTRY BSC','BIOCHEMISTRY BSC','CURRENT'),
('BLS','BLS','CURRENT'),
('BM','BM','CURRENT'),
('BM (Hons)','BM (Hons)','CURRENT'),
('BM Bachelor of Medicine','BM Bachelor of Medicine','CURRENT'),
('BM Bch','BM Bch','CURRENT'),
('BM BCh  MRCGP  DRCOG','BM BCh  MRCGP  DRCOG','CURRENT'),
('BM BCh (Clinical)','BM BCh (Clinical)','CURRENT'),
('BM BCh (Oxon)','BM BCh (Oxon)','CURRENT'),
('BM BcH MRCGP DRCOG FP Cert','BM BcH MRCGP DRCOG FP Cert','CURRENT'),
('BM BcH MRCP DCH DRCOG MRCGP','BM BcH MRCP DCH DRCOG MRCGP','CURRENT'),
('BM BCh(Hons)','BM BCh(Hons)','CURRENT'),
('BM BChOxford','BM BChOxford','CURRENT'),
('BM BCR','BM BCR','CURRENT'),
('BM BS','BM BS','CURRENT'),
('BM BS (Hons)','BM BS (Hons)','CURRENT'),
('BM BS BMedSci','BM BS BMedSci','CURRENT'),
('BM BS DFFP BMedSci','BM BS DFFP BMedSci','CURRENT'),
('BM BS(Hons)','BM BS(Hons)','CURRENT'),
('BM BS, DRCOG','BM BS, DRCOG','CURRENT'),
('BM BSNottm','BM BSNottm','CURRENT'),
('BM Hons','BM Hons','CURRENT'),
('BM MB','BM MB','CURRENT'),
('BM Soton','BM Soton','CURRENT'),
('BM. BS.','BM. BS.','CURRENT'),
('BMBC','BMBC','CURRENT'),
('BMBS (Hons)','BMBS (Hons)','CURRENT'),
('BMBS MRCGP FP Cert','BMBS MRCGP FP Cert','CURRENT'),
('BMBS,  BmedSci','BMBS,  BmedSci','CURRENT'),
('BMBSC','BMBSC','CURRENT'),
('BMCh','BMCh','CURRENT'),
('BMed Sci 1992, BMBS 1994','BMed Sci 1992, BMBS 1994','CURRENT'),
('BMed Sci, BMBS','BMed Sci, BMBS','CURRENT'),
('BMed/Sur','BMed/Sur','CURRENT'),
('BMedSc','BMedSc','CURRENT'),
('BMedSci (Hons) Public Health','BMedSci (Hons) Public Health','CURRENT'),
('BMedSciBMBS','BMedSciBMBS','CURRENT'),
('BMMCh','BMMCh','CURRENT'),
('BN BCH','BN BCH','CURRENT'),
('Board Certification in Internal Medicien (USA)','Board Certification in Internal Medicien (USA)','CURRENT'),
('Bpharm','Bpharm','CURRENT'),
('Bradford Royal Infirmary- Regi','Bradford Royal Infirmary- Regi','CURRENT'),
('BS Bachelor of Surgery','BS Bachelor of Surgery','CURRENT'),
('BSc','BSc','CURRENT'),
('BSc - 2:1 Honors in Medical Imaging and Visualisation','BSc - 2:1 Honors in Medical Imaging and Visualisation','CURRENT'),
('BSc (Hons) - Sport Science with Management','BSc (Hons) - Sport Science with Management','CURRENT'),
('BSc (Hons) Anatomy','BSc (Hons) Anatomy','CURRENT'),
('BSc (Hons) Health Science Masters in Public Health','BSc (Hons) Health Science Masters in Public Health','CURRENT'),
('BSc (Hons) Health Studies (Health Promotion Pathway)','BSc (Hons) Health Studies (Health Promotion Pathway)','CURRENT'),
('BSc (hons) Medical Informatics','BSc (hons) Medical Informatics','CURRENT'),
('BSc (Hons) Physiological Sciences','BSc (Hons) Physiological Sciences','CURRENT'),
('BSc (Hons) Physiology, MBChB','BSc (Hons) Physiology, MBChB','CURRENT'),
('BSc (Hons) Psychology','BSc (Hons) Psychology','CURRENT'),
('BSc (Med Sci)','BSc (Med Sci)','CURRENT'),
('BSc (Physiology)','BSc (Physiology)','CURRENT'),
('BSc Adult Nursing','BSc Adult Nursing','CURRENT'),
('BSc Anthropology','BSc Anthropology','CURRENT'),
('BSc Biochemistry (Medical)','BSc Biochemistry (Medical)','CURRENT'),
('BSc Biological Sciences (Pharmacology)','BSc Biological Sciences (Pharmacology)','CURRENT'),
('BSc Biology','BSc Biology','CURRENT'),
('BSc Biomedical Science','BSc Biomedical Science','CURRENT'),
('Bsc Bsur','Bsc Bsur','CURRENT'),
('BSc Cell Biology','BSc Cell Biology','CURRENT'),
('BSc DFFP','BSc DFFP','CURRENT'),
('BSc Environmental Science','BSc Environmental Science','CURRENT'),
('BSc Environmental Sciences','BSc Environmental Sciences','CURRENT'),
('Bsc Epidemiology & Medical Sta','Bsc Epidemiology & Medical Sta','CURRENT'),
('BSc Genetics','BSc Genetics','CURRENT'),
('BSc Health Studies','BSc Health Studies','CURRENT'),
('BSc History Philosophy and Social Studies of Science','BSc History Philosophy and Social Studies of Science','CURRENT'),
('BSc Hons Physiology, MB ChB DO','BSc Hons Physiology, MB ChB DO','CURRENT'),
('BSc Hons Physiology, MB ChB, D','BSc Hons Physiology, MB ChB, D','CURRENT'),
('BSc in Medical Sciences with Immunity &  Infection','BSc in Medical Sciences with Immunity &  Infection','CURRENT'),
('BSc Joint Honours Biological Sciences','BSc Joint Honours Biological Sciences','CURRENT'),
('BSc MB ChB DGM DRCOG MRCGP','BSc MB ChB DGM DRCOG MRCGP','CURRENT'),
('BSc MB ChB DRCOG DCH MRCGP','BSc MB ChB DRCOG DCH MRCGP','CURRENT'),
('BSc MB ChB MRCGP','BSc MB ChB MRCGP','CURRENT'),
('BSc MBBCH MRCP MRCGP','BSc MBBCH MRCP MRCGP','CURRENT'),
('BSc MBBS FRCA','BSc MBBS FRCA','CURRENT'),
('BSc MBChB MRCP MRCGP','BSc MBChB MRCP MRCGP','CURRENT'),
('BSc Med Sci, MBChB, DRCOG, FP','BSc Med Sci, MBChB, DRCOG, FP','CURRENT'),
('BSc MRCGP','BSc MRCGP','CURRENT'),
('BSc Nursing Studies','BSc Nursing Studies','CURRENT'),
('BSc Physiology','BSc Physiology','CURRENT'),
('BSc Psychology','BSc Psychology','CURRENT'),
('BSc(Hon) MBChB MRCGP DRCOG','BSc(Hon) MBChB MRCGP DRCOG','CURRENT'),
('BSc(Hons) MBChB MRCGP DCH DipI','BSc(Hons) MBChB MRCGP DCH DipI','CURRENT'),
('BSc. Biological Sciences','BSc. Biological Sciences','CURRENT'),
('BSc. Physiology','BSc. Physiology','CURRENT'),
('BScC, MBCHB, DRCOG, DFFP, MRCG','BScC, MBCHB, DRCOG, DFFP, MRCG','CURRENT'),
('BSCCP in colposcopy','BSCCP in colposcopy','CURRENT'),
('BScHons','BScHons','CURRENT'),
('BSS','BSS','CURRENT'),
('Cand Med et Chir','Cand Med et Chir','CURRENT'),
('Canditatus Medicinae et Chirurgiae','Canditatus Medicinae et Chirurgiae','CURRENT'),
('CBiol','CBiol','CURRENT'),
('CCBST','CCBST','CURRENT'),
('CChem MRSC','CChem MRSC','CURRENT'),
('CCRISP','CCRISP','CURRENT'),
('CCST','CCST','CURRENT'),
('CELL BIOLOGY BSC 2.1','CELL BIOLOGY BSC 2.1','CURRENT'),
('Cert HSMM','Cert HSMM','CURRENT'),
('Cert in PHM','Cert in PHM','CURRENT'),
('Certificate College of Family Practice Canada','Certificate College of Family Practice Canada','CURRENT'),
('Certificate in Child Development','Certificate in Child Development','CURRENT'),
('Certificate in Education','Certificate in Education','CURRENT'),
('Certificate in Family Planning','Certificate in Family Planning','CURRENT'),
('Certificate in Health Economics','Certificate in Health Economics','CURRENT'),
('Certificate in Health Education','Certificate in Health Education','CURRENT'),
('Certificate in Health Research','Certificate in Health Research','CURRENT'),
('Certificate in Occupational Health','Certificate in Occupational Health','CURRENT'),
('Certificate in Teaching','Certificate in Teaching','CURRENT'),
('Certificate in Teaching (QESP 1)','Certificate in Teaching (QESP 1)','CURRENT'),
('Certificate of Advanced Study in Health Management','Certificate of Advanced Study in Health Management','CURRENT'),
('Certificate of Medical Education','Certificate of Medical Education','CURRENT'),
('Ch B','Ch B','CURRENT'),
('ChB Bachelor of Surgery','ChB Bachelor of Surgery','CURRENT'),
('Child Health Surveillance','Child Health Surveillance','CURRENT'),
('Counselling & Dev of Learning','Counselling & Dev of Learning','CURRENT'),
('CPR Performance Test','CPR Performance Test','CURRENT'),
('CSCT','CSCT','CURRENT'),
('D Med','D Med','CURRENT'),
('D.Obst','D.Obst','CURRENT'),
('DA (Diploma in Anaesthesia)','DA (Diploma in Anaesthesia)','CURRENT'),
('DAvMed','DAvMed','CURRENT'),
('DCH, India','DCH, India','CURRENT'),
('DCP','DCP','CURRENT'),
('DCR','DCR','CURRENT'),
('DDM','DDM','CURRENT'),
('DDPH','DDPH','CURRENT'),
('DDPHRCS','DDPHRCS','CURRENT'),
('DDS Dental Degree','DDS Dental Degree','CURRENT'),
('Degree Geography BSc','Degree Geography BSc','CURRENT'),
('Degree in Dentistry','Degree in Dentistry','CURRENT'),
('Degree in General Surgery','Degree in General Surgery','CURRENT'),
('Degree in Medicine','Degree in Medicine','CURRENT'),
('Degree in Medicine & Surgery','Degree in Medicine & Surgery','CURRENT'),
('Degree of Bachelor of Medicine','Degree of Bachelor of Medicine','CURRENT'),
('DFSRH','DFSRH','CURRENT'),
('DG','DG','CURRENT'),
('DGH','DGH','CURRENT'),
('DGO','DGO','CURRENT'),
('DHC','DHC','CURRENT'),
('DIC','DIC','CURRENT'),
('DICM','DICM','CURRENT'),
('DICM Module 1','DICM Module 1','CURRENT'),
('DICM Module 2','DICM Module 2','CURRENT'),
('DIMC','DIMC','CURRENT'),
('DIP - MEDICAL JURISPRUDENCE','DIP - MEDICAL JURISPRUDENCE','CURRENT'),
('Dip Clinical Hypnotherapy','Dip Clinical Hypnotherapy','CURRENT'),
('DIP CS (CHRISTIAN STUDIES)','DIP CS (CHRISTIAN STUDIES)','CURRENT'),
('Dip DS','Dip DS','CURRENT'),
('Dip IMC','Dip IMC','CURRENT'),
('Dip In Anaesthesia','Dip In Anaesthesia','CURRENT'),
('Dip in Epidemiology (FPHM)','Dip in Epidemiology (FPHM)','CURRENT'),
('Dip in Preventative & Curative Med','Dip in Preventative & Curative Med','CURRENT'),
('Dip In Therapeutics','Dip In Therapeutics','CURRENT'),
('Dip in Tropical Medicine & Hygience 95, London U','Dip in Tropical Medicine & Hygience 95, London U','CURRENT'),
('Dip Med Acup','Dip Med Acup','CURRENT'),
('Dip N.B. (Psychiatry)','Dip N.B. (Psychiatry)','CURRENT'),
('Dip of Specialist in Nuclear Medicine','Dip of Specialist in Nuclear Medicine','CURRENT'),
('Dip Phys','Dip Phys','CURRENT'),
('DIP RC Path','DIP RC Path','CURRENT'),
('Dip RCPath','Dip RCPath','CURRENT'),
('Dip Sports Medicine','Dip Sports Medicine','CURRENT'),
('Dip Venerology','Dip Venerology','CURRENT'),
('Dip. GUM','Dip. GUM','CURRENT'),
('Dip. HIV','Dip. HIV','CURRENT'),
('DipATS','DipATS','CURRENT'),
('DipCB','DipCB','CURRENT'),
('DipDS','DipDS','CURRENT'),
('DipFP','DipFP','CURRENT'),
('DipGeriatricMed','DipGeriatricMed','CURRENT'),
('DipGUM','DipGUM','CURRENT'),
('DIPIMCRES','DIPIMCRES','CURRENT'),
('Dipl. Ortho.','Dipl. Ortho.','CURRENT'),
('Diplma in Public Health','Diplma in Public Health','CURRENT'),
('Diploma (Diabetology)','Diploma (Diabetology)','CURRENT'),
('Diploma Advanced Ultasound Scanning','Diploma Advanced Ultasound Scanning','CURRENT'),
('Diploma in American Board Family Practice','Diploma in American Board Family Practice','CURRENT'),
('Diploma in Anaesthesia','Diploma in Anaesthesia','CURRENT'),
('Diploma in anaesthetics, MD (India)','Diploma in anaesthetics, MD (India)','CURRENT'),
('Diploma in Aviation Medicine','Diploma in Aviation Medicine','CURRENT'),
('Diploma in Child Health','Diploma in Child Health','CURRENT'),
('Diploma in Clinical Pathology','Diploma in Clinical Pathology','CURRENT'),
('Diploma in Clinical Pharmacy','Diploma in Clinical Pharmacy','CURRENT'),
('Diploma in Dermatology','Diploma in Dermatology','CURRENT'),
('Diploma in Faculty of Family Planning','Diploma in Faculty of Family Planning','CURRENT'),
('Diploma in Family Planning','Diploma in Family Planning','CURRENT'),
('Diploma in Geriatric Medicine','Diploma in Geriatric Medicine','CURRENT'),
('Diploma in Immunology','Diploma in Immunology','CURRENT'),
('Diploma in Laryngology and Otology','Diploma in Laryngology and Otology','CURRENT'),
('Diploma in Medical Education','Diploma in Medical Education','CURRENT'),
('Diploma in Medicine','Diploma in Medicine','CURRENT'),
('Diploma in Medicine and Surgery','Diploma in Medicine and Surgery','CURRENT'),
('Diploma in Obstetrics','Diploma in Obstetrics','CURRENT'),
('Diploma in Obstetrics and Gynaecology','Diploma in Obstetrics and Gynaecology','CURRENT'),
('Diploma in Obstetrics and Medical Gynaecology','Diploma in Obstetrics and Medical Gynaecology','CURRENT'),
('Diploma in Occupational Medicine','Diploma in Occupational Medicine','CURRENT'),
('Diploma in Ophthalmology (RCSI)','Diploma in Ophthalmology (RCSI)','CURRENT'),
('Diploma in Orthopaedics','Diploma in Orthopaedics','CURRENT'),
('Diploma in Paediatric Nutrition','Diploma in Paediatric Nutrition','CURRENT'),
('Diploma in Paediatrics','Diploma in Paediatrics','CURRENT'),
('Diploma in Palliative Medicine','Diploma in Palliative Medicine','CURRENT'),
('Diploma in Postgraduate Dental Studies','Diploma in Postgraduate Dental Studies','CURRENT'),
('Diploma in Psychiatry','Diploma in Psychiatry','CURRENT'),
('Diploma in Psychological Medicine','Diploma in Psychological Medicine','CURRENT'),
('Diploma in Regional Anaesthesia','Diploma in Regional Anaesthesia','CURRENT'),
('Diploma in Tropical Child Health','Diploma in Tropical Child Health','CURRENT'),
('Diploma in Tropical Medicine and Hygiene','Diploma in Tropical Medicine and Hygiene','CURRENT'),
('Diploma in Venereology and HIV','Diploma in Venereology and HIV','CURRENT'),
('Diploma of Clinical Pathology','Diploma of Clinical Pathology','CURRENT'),
('Diploma of Faculty of Family Planning','Diploma of Faculty of Family Planning','CURRENT'),
('Diploma of Family Planning and Reproductive Health','Diploma of Family Planning and Reproductive Health','CURRENT'),
('Diploma of Intensive Care','Diploma of Intensive Care','CURRENT'),
('Diploma of Obstetrics (New Zealand)','Diploma of Obstetrics (New Zealand)','CURRENT'),
('Diploma of Sports Medicine','Diploma of Sports Medicine','CURRENT'),
('Diploma of University Graduation in Medicine','Diploma of University Graduation in Medicine','CURRENT'),
('Diploma Psychosexual Medicine','Diploma Psychosexual Medicine','CURRENT'),
('Diploma, American Board of Paediatrics','Diploma, American Board of Paediatrics','CURRENT'),
('Diplomas in Anaesthetics','Diplomas in Anaesthetics','CURRENT'),
('Diplomate National Board (Obstetrics & Gynaecology','Diplomate National Board (Obstetrics & Gynaecology','CURRENT'),
('Diplomate of National Board (orthopaedics)','Diplomate of National Board (orthopaedics)','CURRENT'),
('Diplome Federal','Diplome Federal','CURRENT'),
('DipMentalHealth','DipMentalHealth','CURRENT'),
('DipObst&Gynae','DipObst&Gynae','CURRENT'),
('Dipolma in Obstetrics & Gynaecology','Dipolma in Obstetrics & Gynaecology','CURRENT'),
('Dipolma in Tropical Medicine and Hygiene','Dipolma in Tropical Medicine and Hygiene','CURRENT'),
('DLORCS','DLORCS','CURRENT'),
('DM (Bombay)','DM (Bombay)','CURRENT'),
('DM (Cardiology)','DM (Cardiology)','CURRENT'),
('DM (Endo)','DM (Endo)','CURRENT'),
('DM (neurol)','DM (neurol)','CURRENT'),
('DMD','DMD','CURRENT'),
('DMRD','DMRD','CURRENT'),
('DNB (Anaesthesia)','DNB (Anaesthesia)','CURRENT'),
('DNB (Med)','DNB (Med)','CURRENT'),
('DNB (neurol)','DNB (neurol)','CURRENT'),
('DNB (O&G)','DNB (O&G)','CURRENT'),
('DNB (Orth)','DNB (Orth)','CURRENT'),
('DNB (PMR)','DNB (PMR)','CURRENT'),
('DObsRCP1','DObsRCP1','CURRENT'),
('Docc Med','Docc Med','CURRENT'),
('DOccMed','DOccMed','CURRENT'),
('Docteur en chirurgie dentaire','Docteur en chirurgie dentaire','CURRENT'),
('Doctor - Medic','Doctor - Medic','CURRENT'),
('Doctor (Vrach) Primary Medical Qualification','Doctor (Vrach) Primary Medical Qualification','CURRENT'),
('Doctor in Dentistry','Doctor in Dentistry','CURRENT'),
('Doctor of Dental Surgery (DDS)','Doctor of Dental Surgery (DDS)','CURRENT'),
('Doctor of Dentistry (DD)','Doctor of Dentistry (DD)','CURRENT'),
('Doctor of Medical Dentistry (DrMedDent)','Doctor of Medical Dentistry (DrMedDent)','CURRENT'),
('Doctoral Thesis','Doctoral Thesis','CURRENT'),
('Doctors','Doctors','CURRENT'),
('DOHNS','DOHNS','CURRENT'),
('DO-HNS','DO-HNS','CURRENT'),
('DO-HNS Part 1','DO-HNS Part 1','CURRENT'),
('DO-HNS Part 2','DO-HNS Part 2','CURRENT'),
('DPFP','DPFP','CURRENT'),
('Dphil','Dphil','CURRENT'),
('Dphil Chemistry','Dphil Chemistry','CURRENT'),
('DPM','DPM','CURRENT'),
('DPP','DPP','CURRENT'),
('DR COG','DR COG','CURRENT'),
('Dr Med','Dr Med','CURRENT'),
('Dr Med Dent','Dr Med Dent','CURRENT'),
('Dr Med Univ','Dr Med Univ','CURRENT'),
('Dr of Medicine','Dr of Medicine','CURRENT'),
('Dr.Med','Dr.Med','CURRENT'),
('DRCOG DFFP FP Cert','DRCOG DFFP FP Cert','CURRENT'),
('DRCOG, MRCGP','DRCOG, MRCGP','CURRENT'),
('DTM','DTM','CURRENT'),
('DTMBH','DTMBH','CURRENT'),
('ECFMG','ECFMG','CURRENT'),
('Economics and International Development','Economics and International Development','CURRENT'),
('EDIC','EDIC','CURRENT'),
('Educational Commission for Foreign Medical Graduat','Educational Commission for Foreign Medical Graduat','CURRENT'),
('Educational Supervisor (OTHER)','Educational Supervisor (OTHER)','CURRENT'),
('Educational Supervisor (QESP 1)','Educational Supervisor (QESP 1)','CURRENT'),
('Educational Supervisor (QESP 2)','Educational Supervisor (QESP 2)','CURRENT'),
('Emergency Medical Accident Services','Emergency Medical Accident Services','CURRENT'),
('EPLS','EPLS','CURRENT'),
('European Diploma Intensive Care Part 1','European Diploma Intensive Care Part 1','CURRENT'),
('FACRRM (Australia)','FACRRM (Australia)','CURRENT'),
('Family Planning','Family Planning','CURRENT'),
('Family Planning Certificate','Family Planning Certificate','CURRENT'),
('Family Planning Certificate, 1','Family Planning Certificate, 1','CURRENT'),
('Family Planning Instructor','Family Planning Instructor','CURRENT'),
('FCA RCSI','FCA RCSI','CURRENT'),
('FCARCSI','FCARCSI','CURRENT'),
('FCARCSI Final Oral Viva','FCARCSI Final Oral Viva','CURRENT'),
('FCARCSI Final Written','FCARCSI Final Written','CURRENT'),
('fce','fce','CURRENT'),
('FCEM','FCEM','CURRENT'),
('FCEM Section A (Academic): CTR Viva','FCEM Section A (Academic): CTR Viva','CURRENT'),
('FCEM Section A (Academic): SAQ','FCEM Section A (Academic): SAQ','CURRENT'),
('FCEM Section B: Management Viva','FCEM Section B: Management Viva','CURRENT'),
('FCEM Section C (Clinical): OSCE','FCEM Section C (Clinical): OSCE','CURRENT'),
('FCEM Section C (Clinical): SAQ','FCEM Section C (Clinical): SAQ','CURRENT'),
('FCOG(SA)','FCOG(SA)','CURRENT'),
('FCPS (Gen Surg)','FCPS (Gen Surg)','CURRENT'),
('FCPS 1','FCPS 1','CURRENT'),
('FCPS I','FCPS I','CURRENT'),
('FCPS(PAK)','FCPS(PAK)','CURRENT'),
('FDS','FDS','CURRENT'),
('FDS - Primary','FDS - Primary','CURRENT'),
('FDS / FFD RCS or MFDS or equivalent','FDS / FFD RCS or MFDS or equivalent','CURRENT'),
('FDSRCPS','FDSRCPS','CURRENT'),
('FEBU','FEBU','CURRENT'),
('Federal diploma of doctor','Federal diploma of doctor','CURRENT'),
('FFA RCS Part 1','FFA RCS Part 1','CURRENT'),
('FFAEM','FFAEM','CURRENT'),
('FFARCS','FFARCS','CURRENT'),
('FFARCS 1','FFARCS 1','CURRENT'),
('FFARCS(I) Part 2','FFARCS(I) Part 2','CURRENT'),
('FFARCSI','FFARCSI','CURRENT'),
('FFARCSI 1 & 2','FFARCSI 1 & 2','CURRENT'),
('FFDRCS(Ire)','FFDRCS(Ire)','CURRENT'),
('FHSM','FHSM','CURRENT'),
('FICS (Hons)','FICS (Hons)','CURRENT'),
('FIMLS','FIMLS','CURRENT'),
('Final Ex','Final Ex','CURRENT'),
('Final Fellowship in Dental Surgery','Final Fellowship in Dental Surgery','CURRENT'),
('FINAL FRCA','FINAL FRCA','CURRENT'),
('Fit to Lead','Fit to Lead','CURRENT'),
('FJFICM (Aus)','FJFICM (Aus)','CURRENT'),
('FMCOG','FMCOG','CURRENT'),
('FMCS','FMCS','CURRENT'),
('FMGEMS','FMGEMS','CURRENT'),
('FR CA','FR CA','CURRENT'),
('FRACDS','FRACDS','CURRENT'),
('FRACGP','FRACGP','CURRENT'),
('FRACP','FRACP','CURRENT'),
('FRACS (Gen.Surg)','FRACS (Gen.Surg)','CURRENT'),
('FRACS (Paed Surg)','FRACS (Paed Surg)','CURRENT'),
('FRACS Part II','FRACS Part II','CURRENT'),
('FRC Ophth','FRC Ophth','CURRENT'),
('FRCA (South Africa)','FRCA (South Africa)','CURRENT'),
('FRCA Final','FRCA Final','CURRENT'),
('FRCA Final (SOE)','FRCA Final (SOE)','CURRENT'),
('FRCA Final (Written)','FRCA Final (Written)','CURRENT'),
('FRCA I','FRCA I','CURRENT'),
('FRCA I & II','FRCA I & II','CURRENT'),
('FRCA I II + FINAL','FRCA I II + FINAL','CURRENT'),
('FRCA MD','FRCA MD','CURRENT'),
('FRCA OSCE','FRCA OSCE','CURRENT'),
('FRCA Part One','FRCA Part One','CURRENT'),
('FRCA Part Two','FRCA Part Two','CURRENT'),
('FRCA Primary','FRCA Primary','CURRENT'),
('FRCA Primary (MCQ)','FRCA Primary (MCQ)','CURRENT'),
('FRCA Primary (OSCE)','FRCA Primary (OSCE)','CURRENT'),
('FRCA Primary (SOE)','FRCA Primary (SOE)','CURRENT'),
('FRCGP','FRCGP','CURRENT'),
('FRCO','FRCO','CURRENT'),
('FRCO phth','FRCO phth','CURRENT'),
('FRCOG','FRCOG','CURRENT'),
('FRCOphth','FRCOphth','CURRENT'),
('FRCOPhth 1','FRCOPhth 1','CURRENT'),
('FRCOphth 2','FRCOphth 2','CURRENT'),
('FRCP','FRCP','CURRENT'),
('FRCP(Canada)','FRCP(Canada)','CURRENT'),
('FRCPath','FRCPath','CURRENT'),
('FRCPath Part 1','FRCPath Part 1','CURRENT'),
('FRCPath Part 1 Examination in Chemical Pathology','FRCPath Part 1 Examination in Chemical Pathology','CURRENT'),
('FRCPath Part 1 Examination in Histopathology','FRCPath Part 1 Examination in Histopathology','CURRENT'),
('FRCPath Part 1 Examination in Medical Microbiology','FRCPath Part 1 Examination in Medical Microbiology','CURRENT'),
('FRCPath Part 2','FRCPath Part 2','CURRENT'),
('FRCPath Part 2 Examination in Chemical Pathology','FRCPath Part 2 Examination in Chemical Pathology','CURRENT'),
('FRCPath Part 2 Examination in Histopathology','FRCPath Part 2 Examination in Histopathology','CURRENT'),
('FRCPath Part 2 Examination in Medical Microbiology','FRCPath Part 2 Examination in Medical Microbiology','CURRENT'),
('FRCPath Year Assessment','FRCPath Year Assessment','CURRENT'),
('FRCPS','FRCPS','CURRENT'),
('FRCPS (Glasgow)','FRCPS (Glasgow)','CURRENT'),
('FRCR','FRCR','CURRENT'),
('FRCR - Part 2A','FRCR - Part 2A','CURRENT'),
('FRCR - Part 2B','FRCR - Part 2B','CURRENT'),
('FRCR  Part A Fellowship Clinical Radiology','FRCR  Part A Fellowship Clinical Radiology','CURRENT'),
('FRCR 1','FRCR 1','CURRENT'),
('FRCR 11A','FRCR 11A','CURRENT'),
('FRCR 11B','FRCR 11B','CURRENT'),
('FRCR 2a Cardiovascular','FRCR 2a Cardiovascular','CURRENT'),
('FRCR 2a MSK','FRCR 2a MSK','CURRENT'),
('FRCR 2a Musculoskeletal Radiology','FRCR 2a Musculoskeletal Radiology','CURRENT'),
('FRCR 2a Neuro','FRCR 2a Neuro','CURRENT'),
('FRCR 2a Neuroradiology','FRCR 2a Neuroradiology','CURRENT'),
('FRCR Final Examination Part A','FRCR Final Examination Part A','CURRENT'),
('FRCR Final Examination Part B','FRCR Final Examination Part B','CURRENT'),
('FRCR Final Fellowship Clinical Radiology','FRCR Final Fellowship Clinical Radiology','CURRENT'),
('FRCR First Examination','FRCR First Examination','CURRENT'),
('FRCR Part 1','FRCR Part 1','CURRENT'),
('FRCR Part 2','FRCR Part 2','CURRENT'),
('FRCR Part 2B Fellowship Clinical Radiology','FRCR Part 2B Fellowship Clinical Radiology','CURRENT'),
('FRCS (A&E)','FRCS (A&E)','CURRENT'),
('FRCS (A)','FRCS (A)','CURRENT'),
('FRCS (Ed)','FRCS (Ed)','CURRENT'),
('FRCS (Edinburgh)','FRCS (Edinburgh)','CURRENT'),
('FRCS (England)','FRCS (England)','CURRENT'),
('FRCS (ENT)','FRCS (ENT)','CURRENT'),
('FRCS (Gen Surg)','FRCS (Gen Surg)','CURRENT'),
('FRCS (Gen Surgery), (Otolaryngology) & (DRL)','FRCS (Gen Surgery), (Otolaryngology) & (DRL)','CURRENT'),
('FRCS (Gen)','FRCS (Gen)','CURRENT'),
('FRCS (Glasg)','FRCS (Glasg)','CURRENT'),
('FRCS (Glasgow)','FRCS (Glasgow)','CURRENT'),
('FRCS (OMFS)','FRCS (OMFS)','CURRENT'),
('FRCS (ORL-HN) Edin, MS (ENT)','FRCS (ORL-HN) Edin, MS (ENT)','CURRENT'),
('FRCS (Orth)','FRCS (Orth)','CURRENT'),
('FRCS (Oto)','FRCS (Oto)','CURRENT'),
('FRCS (Plast)','FRCS (Plast)','CURRENT'),
('FRCS (Tr & Orth) Feb 2000','FRCS (Tr & Orth) Feb 2000','CURRENT'),
('FRCS (Urol)','FRCS (Urol)','CURRENT'),
('FRCS [Ed]','FRCS [Ed]','CURRENT'),
('FRCS [Eng]','FRCS [Eng]','CURRENT'),
('FRCS I','FRCS I','CURRENT'),
('FRCS in Ireland','FRCS in Ireland','CURRENT'),
('FRCS Opthalmology','FRCS Opthalmology','CURRENT'),
('FRCS Orth.Eng','FRCS Orth.Eng','CURRENT'),
('FRCS Part I','FRCS Part I','CURRENT'),
('FRCS Part II','FRCS Part II','CURRENT'),
('FRCS(ORL-HNS)','FRCS(ORL-HNS)','CURRENT'),
('FRCS(Oto)','FRCS(Oto)','CURRENT'),
('FRCSEd','FRCSEd','CURRENT'),
('FRCSEd [Plast]','FRCSEd [Plast]','CURRENT'),
('FRCSI (Otol)','FRCSI (Otol)','CURRENT'),
('FRCSOphth','FRCSOphth','CURRENT'),
('FWACS','FWACS','CURRENT'),
('GDS','GDS','CURRENT'),
('General Human Medicine','General Human Medicine','CURRENT'),
('General Medicine','General Medicine','CURRENT'),
('GERM CER','GERM CER','CURRENT'),
('Grading (M Sc) in General Surgery','Grading (M Sc) in General Surgery','CURRENT'),
('Graduate Diploma in Dentistry (Grad Dip Dent)','Graduate Diploma in Dentistry (Grad Dip Dent)','CURRENT'),
('Gydytojas','Gydytojas','CURRENT'),
('Hak-Sa','Hak-Sa','CURRENT'),
('Higher Degree of Diploma in Public Health','Higher Degree of Diploma in Public Health','CURRENT'),
('Higher Medical institute Pleven, Bulgaria','Higher Medical institute Pleven, Bulgaria','CURRENT'),
('HLL','HLL','CURRENT'),
('HSC','HSC','CURRENT'),
('ICM Joint CCT: Advanced (Step 2) ICM','ICM Joint CCT: Advanced (Step 2) ICM','CURRENT'),
('ICM Joint CCT: Basic ICM','ICM Joint CCT: Basic ICM','CURRENT'),
('ICM Joint CCT: Complementary Anaesthesia','ICM Joint CCT: Complementary Anaesthesia','CURRENT'),
('ICM Joint CCT: Complementary Medicine','ICM Joint CCT: Complementary Medicine','CURRENT'),
('ICM Joint CCT: Imtermediate (Step 1) ICM','ICM Joint CCT: Imtermediate (Step 1) ICM','CURRENT'),
('Igakushi','Igakushi','CURRENT'),
('Intercollegiate Specialty Exam','Intercollegiate Specialty Exam','CURRENT'),
('Intercollegiate Specialty Fellowship Exam','Intercollegiate Specialty Fellowship Exam','CURRENT'),
('Introductory Course in Occupational Medicine','Introductory Course in Occupational Medicine','CURRENT'),
('IQE','IQE','CURRENT'),
('JCPTGP','JCPTGP','CURRENT'),
('JCPTGP Certificate','JCPTGP Certificate','CURRENT'),
('Joint RCR/RCOG training in O&G','Joint RCR/RCOG training in O&G','CURRENT'),
('L LM RCP L LM RCS','L LM RCP L LM RCS','CURRENT'),
('Lakarexamen','Lakarexamen','CURRENT'),
('Laurea Magistrale in Medicina e Chirurgia','Laurea Magistrale in Medicina e Chirurgia','CURRENT'),
('LCPS Licentiate College of Physicians & Surgeons','LCPS Licentiate College of Physicians & Surgeons','CURRENT'),
('LDS','LDS','CURRENT'),
('Lekarz','Lekarz','CURRENT'),
('Lekarz (Master in Graduate Medicine)','Lekarz (Master in Graduate Medicine)','CURRENT'),
('Lic Med','Lic Med','CURRENT'),
('LIC MS','LIC MS','CURRENT'),
('Lic Odont','Lic Odont','CURRENT'),
('Licenciada en Medicina','Licenciada en Medicina','CURRENT'),
('Licenciada en Medicina y Cirugia','Licenciada en Medicina y Cirugia','CURRENT'),
('Licenciado en Odontologia','Licenciado en Odontologia','CURRENT'),
('License in Medicine & Surgery (Spanish)','License in Medicine & Surgery (Spanish)','CURRENT'),
('LLB','LLB','CURRENT'),
('LLM (Master of Laws)','LLM (Master of Laws)','CURRENT'),
('LMD','LMD','CURRENT'),
('LMS','LMS','CURRENT'),
('LMS (MBBS)','LMS (MBBS)','CURRENT'),
('LMS Licentiate of Medicine & Surgery','LMS Licentiate of Medicine & Surgery','CURRENT'),
('LMSSA Licentiate in Medicine & Surgery - Society of Apothecaries London','LMSSA Licentiate in Medicine & Surgery - Society of Apothecaries London','CURRENT'),
('LMSSALond','LMSSALond','CURRENT'),
('LRCP  MRCS  MBBS  FRCA   MRCGP','LRCP  MRCS  MBBS  FRCA   MRCGP','CURRENT'),
('LRCP & S Irel','LRCP & S Irel','CURRENT'),
('LRCP DA','LRCP DA','CURRENT'),
('LRCP Edin LRCS','LRCP Edin LRCS','CURRENT'),
('LRCP IMBBCh BAO','LRCP IMBBCh BAO','CURRENT'),
('LRCP Licentiate Royal College of Physicians','LRCP Licentiate Royal College of Physicians','CURRENT'),
('LRCP MRCS','LRCP MRCS','CURRENT'),
('LRCP MRCS DRCOG MRCGP','LRCP MRCS DRCOG MRCGP','CURRENT'),
('LRCP MRCS FPA cert','LRCP MRCS FPA cert','CURRENT'),
('LRCP, MRCS','LRCP, MRCS','CURRENT'),
('LRCP.MRCS.DRCOG','LRCP.MRCS.DRCOG','CURRENT'),
('LRCPI Licentiate Royal College of Physicians of Ir','LRCPI Licentiate Royal College of Physicians of Ir','CURRENT'),
('LRCPS Licentiate Royal College of Physicians & Surgeons','LRCPS Licentiate Royal College of Physicians & Surgeons','CURRENT'),
('LRCPS, LRCP, LRCPS','LRCPS, LRCP, LRCPS','CURRENT'),
('LRCS Licentiate Royal College of Surgeons','LRCS Licentiate Royal College of Surgeons','CURRENT'),
('LRCSI Licentiate Royal College of Surgeons of Ireland','LRCSI Licentiate Royal College of Surgeons of Ireland','CURRENT'),
('LSA Licentiate Society of Apothecaries London','LSA Licentiate Society of Apothecaries London','CURRENT'),
('M A','M A','CURRENT'),
('M B B S','M B B S','CURRENT'),
('M d','M d','CURRENT'),
('M Fam MED','M Fam MED','CURRENT'),
('M Med Sci','M Med Sci','CURRENT'),
('M Orth','M Orth','CURRENT'),
('M PsychMed','M PsychMed','CURRENT'),
('M Rad','M Rad','CURRENT'),
('M.D.','M.D.','CURRENT'),
('M.Med (Obs&Gyn)','M.Med (Obs&Gyn)','CURRENT'),
('M.Med Sci.','M.Med Sci.','CURRENT'),
('M.Orth R.C.S','M.Orth R.C.S','CURRENT'),
('M.Phil','M.Phil','CURRENT'),
('M.Sc','M.Sc','CURRENT'),
('M.SC.','M.SC.','CURRENT'),
('MA','MA','CURRENT'),
('MA (Hons)','MA (Hons)','CURRENT'),
('MA (Hons) Geography and Social Anthropology','MA (Hons) Geography and Social Anthropology','CURRENT'),
('MA (Hons) Psychology','MA (Hons) Psychology','CURRENT'),
('MA (OXON)','MA (OXON)','CURRENT'),
('MA BM BCh DCH DObstRCOG MRCGP','MA BM BCh DCH DObstRCOG MRCGP','CURRENT'),
('MA BM BCh MRCGP DRCOG','MA BM BCh MRCGP DRCOG','CURRENT'),
('MA DROG','MA DROG','CURRENT'),
('MA Kings College Cambridge','MA Kings College Cambridge','CURRENT'),
('MA MB B CHIR DRCOG MRCGP','MA MB B CHIR DRCOG MRCGP','CURRENT'),
('MA MB Bchir DRCOG','MA MB Bchir DRCOG','CURRENT'),
('MA MB Bchir MRCP MRCGP DRCOG','MA MB Bchir MRCP MRCGP DRCOG','CURRENT'),
('MA Med Sci','MA Med Sci','CURRENT'),
('MA MEDSC','MA MEDSC','CURRENT'),
('MA(Cantab)BMBCh(Oxon','MA(Cantab)BMBCh(Oxon','CURRENT'),
('MA, MBBS, MRCGP, DCH, DRCOG, F','MA, MBBS, MRCGP, DCH, DRCOG, F','CURRENT'),
('MA,MB,BChir,MRCGP','MA,MB,BChir,MRCGP','CURRENT'),
('MACP (USA)','MACP (USA)','CURRENT'),
('Magister','Magister','CURRENT'),
('Magistri Scientarum (M S)','Magistri Scientarum (M S)','CURRENT'),
('Master in Dental Public Health','Master in Dental Public Health','CURRENT'),
('Master of Pharmacy','Master of Pharmacy','CURRENT'),
('Master of Science Social Epidemiology','Master of Science Social Epidemiology','CURRENT'),
('Master P H','Master P H','CURRENT'),
('Masters','Masters','CURRENT'),
('Masters Degree in Health Science and Medicine','Masters Degree in Health Science and Medicine','CURRENT'),
('Masters in Assisted Reproduction Technology','Masters in Assisted Reproduction Technology','CURRENT'),
('Masters in Medical Education','Masters in Medical Education','CURRENT'),
('Masters in Radiology','Masters in Radiology','CURRENT'),
('Masters of Public Health','Masters of Public Health','CURRENT'),
('Masters of Public Health (MPH)','Masters of Public Health (MPH)','CURRENT'),
('MB  BS  DCH  DRCOG  MRCGP','MB  BS  DCH  DRCOG  MRCGP','CURRENT'),
('MB B Chr','MB B Chr','CURRENT'),
('MB BA','MB BA','CURRENT'),
('MB BAO','MB BAO','CURRENT'),
('MB Bao Bch BMedSci','MB Bao Bch BMedSci','CURRENT'),
('MB BB','MB BB','CURRENT'),
('MB BC','MB BC','CURRENT'),
('MB BCh','MB BCh','CURRENT'),
('MB BCh BAO','MB BCh BAO','CURRENT'),
('MB BCh BAO B Med Sci (Hons)','MB BCh BAO B Med Sci (Hons)','CURRENT'),
('MB BCh BAO MRCP MRCGP','MB BCh BAO MRCP MRCGP','CURRENT'),
('MB BCh BAO(NUI) LRCP&SI','MB BCh BAO(NUI) LRCP&SI','CURRENT'),
('MB BCh O','MB BCh O','CURRENT'),
('MB BCh, BAO, BMed Sc','MB BCh, BAO, BMed Sc','CURRENT'),
('MB BChB','MB BChB','CURRENT'),
('MB BChBAO','MB BChBAO','CURRENT'),
('MB BChBelf','MB BChBelf','CURRENT'),
('MB BChDubl','MB BChDubl','CURRENT'),
('MB BChir','MB BChir','CURRENT'),
('MB Bchir DRCOG MRCGP','MB Bchir DRCOG MRCGP','CURRENT'),
('MB Bchir FRCS(HAS EQUIVALENT','MB Bchir FRCS(HAS EQUIVALENT','CURRENT'),
('MB BChirCamb','MB BChirCamb','CURRENT'),
('MB BChNUIrel','MB BChNUIrel','CURRENT'),
('MB BChWales','MB BChWales','CURRENT'),
('MB BS','MB BS','CURRENT'),
('MB BS  MRCGP   DRCOG   FPCERT','MB BS  MRCGP   DRCOG   FPCERT','CURRENT'),
('MB BS (BSc)','MB BS (BSc)','CURRENT'),
('MB BS 1999 Lond','MB BS 1999 Lond','CURRENT'),
('MB BS with merit','MB BS with merit','CURRENT'),
('MB BS(Hons)','MB BS(Hons)','CURRENT'),
('MB BS, DCCH, DRCOG, Dip Pall M','MB BS, DCCH, DRCOG, Dip Pall M','CURRENT'),
('MB BS, DCH, DMS','MB BS, DCH, DMS','CURRENT'),
('MB BS, MRCGP DRCPG','MB BS, MRCGP DRCPG','CURRENT'),
('MB BS, MRCGP, DRCOG','MB BS, MRCGP, DRCOG','CURRENT'),
('MB BS, MRCP, MRCGP','MB BS, MRCP, MRCGP','CURRENT'),
('MB BS/BSc','MB BS/BSc','CURRENT'),
('MB BS5','MB BS5','CURRENT'),
('MB BSc','MB BSc','CURRENT'),
('MB BSLond','MB BSLond','CURRENT'),
('MB BSNcle','MB BSNcle','CURRENT'),
('MB Ch B DCH(equivalant MRCGP','MB Ch B DCH(equivalant MRCGP','CURRENT'),
('MB ChB  DRCOG MRCGP','MB ChB  DRCOG MRCGP','CURRENT'),
('MB ChB  MRCGP','MB ChB  MRCGP','CURRENT'),
('mb chB (Edin) DFFP','mb chB (Edin) DFFP','CURRENT'),
('MB ChB (Leeds), MRCP (UK), DRC','MB ChB (Leeds), MRCP (UK), DRC','CURRENT'),
('MB ChB (with pre-medical year)','MB ChB (with pre-medical year)','CURRENT'),
('MB ChB DCH DRCOG FP-CERT','MB ChB DCH DRCOG FP-CERT','CURRENT'),
('MB ChB DCH DRCOG MRCGP','MB ChB DCH DRCOG MRCGP','CURRENT'),
('MB ChB DCH DRCOG MRCGP FP Cert','MB ChB DCH DRCOG MRCGP FP Cert','CURRENT'),
('MB ChB DCH DROG MRCGP','MB ChB DCH DROG MRCGP','CURRENT'),
('MB ChB DCH MRCGP','MB ChB DCH MRCGP','CURRENT'),
('MB ChB distinction in biochemi','MB ChB distinction in biochemi','CURRENT'),
('MB ChB DMRT','MB ChB DMRT','CURRENT'),
('MB ChB DObstRCOG','MB ChB DObstRCOG','CURRENT'),
('MB ChB DObstRCOG MRCGP FPA','MB ChB DObstRCOG MRCGP FPA','CURRENT'),
('MB ChB DRCOG DCH MRCGP','MB ChB DRCOG DCH MRCGP','CURRENT'),
('MB ChB DRCOG FFARCS MRCGP','MB ChB DRCOG FFARCS MRCGP','CURRENT'),
('MB ChB DRCOG FRCGP','MB ChB DRCOG FRCGP','CURRENT'),
('MB ChB DRCOG MRCGP','MB ChB DRCOG MRCGP','CURRENT'),
('MB ChB DRCOG MRCGP Cert. Of co','MB ChB DRCOG MRCGP Cert. Of co','CURRENT'),
('MB ChB DRCOG MRCGP FP Cert','MB ChB DRCOG MRCGP FP Cert','CURRENT'),
('MB ChB DRCOG MRCP','MB ChB DRCOG MRCP','CURRENT'),
('MB ChB DRCOG, DCH','MB ChB DRCOG, DCH','CURRENT'),
('MB ChB DRCOG, DFFP','MB ChB DRCOG, DFFP','CURRENT'),
('MB ChB FPCert','MB ChB FPCert','CURRENT'),
('MB ChB FRCGP DobstRCOG','MB ChB FRCGP DobstRCOG','CURRENT'),
('MB ChB Hons','MB ChB Hons','CURRENT'),
('MB ChB MRCGP','MB ChB MRCGP','CURRENT'),
('MB ChB MRCGP DCH DRCOG FPCert','MB ChB MRCGP DCH DRCOG FPCert','CURRENT'),
('MB ChB MRCGP DGM','MB ChB MRCGP DGM','CURRENT'),
('MB ChB MRCGP DRCOG','MB ChB MRCGP DRCOG','CURRENT'),
('MB ChB MRCGP DRCOG FPCert','MB ChB MRCGP DRCOG FPCert','CURRENT'),
('MB ChB MRCGP FP Cert','MB ChB MRCGP FP Cert','CURRENT'),
('MB ChB MRCGP FP Cert DFFD','MB ChB MRCGP FP Cert DFFD','CURRENT'),
('MB ChB MRCP DCH','MB ChB MRCP DCH','CURRENT'),
('MB ChB with Honours','MB ChB with Honours','CURRENT'),
('MB ChB(A100)','MB ChB(A100)','CURRENT'),
('MB ChB(Hons), BSc (H','MB ChB(Hons), BSc (H','CURRENT'),
('MB ChB, DCH','MB ChB, DCH','CURRENT'),
('MB ChB, DCH, MRGCP','MB ChB, DCH, MRGCP','CURRENT'),
('MB ChB, Dip Obst','MB ChB, Dip Obst','CURRENT'),
('MB ChB, Distinction Biochemist','MB ChB, Distinction Biochemist','CURRENT'),
('MB ChB, DRCOG','MB ChB, DRCOG','CURRENT'),
('MB ChB, DRCOG FPCert','MB ChB, DRCOG FPCert','CURRENT'),
('MB ChB, DRCOG, DCH','MB ChB, DRCOG, DCH','CURRENT'),
('MB ChB, DRCOG, DCH, MRCGP','MB ChB, DRCOG, DCH, MRCGP','CURRENT'),
('MB ChB, DRCOG, DF FP','MB ChB, DRCOG, DF FP','CURRENT'),
('MB ChB, DRCOG, DFFP','MB ChB, DRCOG, DFFP','CURRENT'),
('MB ChB, DRCOG, Diploma in Ther','MB ChB, DRCOG, Diploma in Ther','CURRENT'),
('MB ChB, DRCOG, FPCert','MB ChB, DRCOG, FPCert','CURRENT'),
('MB ChB, DRCOG, MRCGP','MB ChB, DRCOG, MRCGP','CURRENT'),
('MB ChB, DRCOG, MRCGP, MRCOphth','MB ChB, DRCOG, MRCGP, MRCOphth','CURRENT'),
('MB ChB, FP Cert, COBC (ACUPUNC','MB ChB, FP Cert, COBC (ACUPUNC','CURRENT'),
('MB ChB, FRCS (Ed), DRCOG','MB ChB, FRCS (Ed), DRCOG','CURRENT'),
('MB ChB, MRCGP','MB ChB, MRCGP','CURRENT'),
('MB ChB, MRCGP, DCH','MB ChB, MRCGP, DCH','CURRENT'),
('MB ChB, MRCGP, DCH, DA, FP Cer','MB ChB, MRCGP, DCH, DA, FP Cer','CURRENT'),
('MB ChB, MRCGP, DRCOG','MB ChB, MRCGP, DRCOG','CURRENT'),
('MB ChB, MRCGP, FPC','MB ChB, MRCGP, FPC','CURRENT'),
('MB ChB, MRCGP, MRCSP','MB ChB, MRCGP, MRCSP','CURRENT'),
('MB ChB, MRCP, DCH, MRCGP','MB ChB, MRCP, DCH, MRCGP','CURRENT'),
('MB ChB,, BSc Pharmacology, MRC','MB ChB,, BSc Pharmacology, MRC','CURRENT'),
('MB ChBAberd','MB ChBAberd','CURRENT'),
('MB ChBBirm','MB ChBBirm','CURRENT'),
('MB ChBBrist','MB ChBBrist','CURRENT'),
('MB ChBDund','MB ChBDund','CURRENT'),
('MB ChBEdin','MB ChBEdin','CURRENT'),
('MB ChBGlasg','MB ChBGlasg','CURRENT'),
('MB ChBLeeds','MB ChBLeeds','CURRENT'),
('MB ChBLeic','MB ChBLeic','CURRENT'),
('MB ChBLpool','MB ChBLpool','CURRENT'),
('MB ChBManc','MB ChBManc','CURRENT'),
('MB ChBSheff','MB ChBSheff','CURRENT'),
('MB ChBStAnd','MB ChBStAnd','CURRENT'),
('MB Chp, DFPS','MB Chp, DFPS','CURRENT'),
('MB LRCPI','MB LRCPI','CURRENT'),
('MB Mch BAO','MB Mch BAO','CURRENT'),
('MB MRCP MRCGP','MB MRCP MRCGP','CURRENT'),
('MB MS','MB MS','CURRENT'),
('MB, BS, BA','MB, BS, BA','CURRENT'),
('MB, BS, DRCOG, MRCGP','MB, BS, DRCOG, MRCGP','CURRENT'),
('MB,Ch.B','MB,Ch.B','CURRENT'),
('MBBA, BCH','MBBA, BCH','CURRENT'),
('MBBAOBCH','MBBAOBCH','CURRENT'),
('MBBCh Bachelor of Medicine and Bachelor of Surgery','MBBCh Bachelor of Medicine and Bachelor of Surgery','CURRENT'),
('MBBCh BAO DCH DObs.MRCG','MBBCh BAO DCH DObs.MRCG','CURRENT'),
('MBBCh MRCGP','MBBCh MRCGP','CURRENT'),
('MBBcH, BMedSci','MBBcH, BMedSci','CURRENT'),
('MBBhB','MBBhB','CURRENT'),
('MBBS  DRCOG','MBBS  DRCOG','CURRENT'),
('MBBS  DRCOG MRCGP - exam','MBBS  DRCOG MRCGP - exam','CURRENT'),
('MBBS - Passed with Distinction','MBBS - Passed with Distinction','CURRENT'),
('MBBS (A100)','MBBS (A100)','CURRENT'),
('MBBS (AICSM)','MBBS (AICSM)','CURRENT'),
('MBBS (Hons)','MBBS (Hons)','CURRENT'),
('MBBS Bachelor of Medicine','MBBS Bachelor of Medicine','CURRENT'),
('MBBS Bachelor of Medicine and Bachelor of Surgery','MBBS Bachelor of Medicine and Bachelor of Surgery','CURRENT'),
('MBBS Bachelor of Medince/ Surg','MBBS Bachelor of Medince/ Surg','CURRENT'),
('MBBS BSc  PhD MRCGP','MBBS BSc  PhD MRCGP','CURRENT'),
('MBBS DCH DRCOG DFFP','MBBS DCH DRCOG DFFP','CURRENT'),
('MBBS DFFM Certificate in Devel','MBBS DFFM Certificate in Devel','CURRENT'),
('MBBS DGM MRCGP','MBBS DGM MRCGP','CURRENT'),
('MBBS DObstRCOG DCH','MBBS DObstRCOG DCH','CURRENT'),
('MBBS DRCOG','MBBS DRCOG','CURRENT'),
('MBBS DRCOG DCH MRCGP FP Cert','MBBS DRCOG DCH MRCGP FP Cert','CURRENT'),
('MBBS DRCOG DFFP MRCGP','MBBS DRCOG DFFP MRCGP','CURRENT'),
('MBBS DRCOG FP Cert JCPTGP','MBBS DRCOG FP Cert JCPTGP','CURRENT'),
('MBBS DRCOG FPCert MRCGP','MBBS DRCOG FPCert MRCGP','CURRENT'),
('MBBS DRCOG FRCGP','MBBS DRCOG FRCGP','CURRENT'),
('MBBS DRCOG JCC Cert MRCGP','MBBS DRCOG JCC Cert MRCGP','CURRENT'),
('MBBS DRCOG MRCGP','MBBS DRCOG MRCGP','CURRENT'),
('MBBS DRCOG MRCGP FP Cert','MBBS DRCOG MRCGP FP Cert','CURRENT'),
('MBBS DRCOG MRCGP FRACGP','MBBS DRCOG MRCGP FRACGP','CURRENT'),
('MBBS Hons','MBBS Hons','CURRENT'),
('MBBS Lond','MBBS Lond','CURRENT'),
('MBBS MRCGP','MBBS MRCGP','CURRENT'),
('MBBS MRCGP DCCH DRCOG','MBBS MRCGP DCCH DRCOG','CURRENT'),
('MBBS MRCGP DCH DRCOG','MBBS MRCGP DCH DRCOG','CURRENT'),
('MBBS MRCGP DCH DRCOG FP Cert','MBBS MRCGP DCH DRCOG FP Cert','CURRENT'),
('MBBS MRCGP DFFP','MBBS MRCGP DFFP','CURRENT'),
('MBBS MRCGP Dip.Obst RCOG','MBBS MRCGP Dip.Obst RCOG','CURRENT'),
('MBBS MRCGP DRCOG','MBBS MRCGP DRCOG','CURRENT'),
('MBBS MRCGP DRCOG BCH','MBBS MRCGP DRCOG BCH','CURRENT'),
('MBBS MRCGP DRCOG DPD','MBBS MRCGP DRCOG DPD','CURRENT'),
('MBBS MRCGP FP Cert','MBBS MRCGP FP Cert','CURRENT'),
('MBBS MRCGP MRCP','MBBS MRCGP MRCP','CURRENT'),
('MBBS MSc (Community Health in','MBBS MSc (Community Health in','CURRENT'),
('MBBS, B.Med.Sci','MBBS, B.Med.Sci','CURRENT'),
('MBBS, DRCOG','MBBS, DRCOG','CURRENT'),
('MBBS, DRCOG, MRCGP, FPA Cert','MBBS, DRCOG, MRCGP, FPA Cert','CURRENT'),
('MBBS, MRCGP','MBBS, MRCGP','CURRENT'),
('MBBS, MRCGP, DA, DRCOG','MBBS, MRCGP, DA, DRCOG','CURRENT'),
('MBBS, MRCP','MBBS, MRCP','CURRENT'),
('MBBS, MRCP, MRCGP, DRCOG, FAMI','MBBS, MRCP, MRCGP, DRCOG, FAMI','CURRENT'),
('MBBS. DRCOG DCH DPD MRCGP','MBBS. DRCOG DCH DPD MRCGP','CURRENT'),
('MBBS; BSc(Hons)','MBBS; BSc(Hons)','CURRENT'),
('MBBS; MBChB','MBBS; MBChB','CURRENT'),
('MBCBh','MBCBh','CURRENT'),
('mbcChB','mbcChB','CURRENT'),
('MBCChB (Hons)','MBCChB (Hons)','CURRENT'),
('MBChB    MRCGP','MBChB    MRCGP','CURRENT'),
('MBChB  DA   DFFP    MRCGP','MBChB  DA   DFFP    MRCGP','CURRENT'),
('MBChB  DRCOG  MRCGP','MBChB  DRCOG  MRCGP','CURRENT'),
('MBChB  MRCP  MRCGP   DCH  D','MBChB  MRCP  MRCGP   DCH  D','CURRENT'),
('MBChB (Distinction)','MBChB (Distinction)','CURRENT'),
('MBChB (expected)','MBChB (expected)','CURRENT'),
('MBChB (Hons','MBChB (Hons','CURRENT'),
('MBChB (Hons in Anatomy)','MBChB (Hons in Anatomy)','CURRENT'),
('MBChB (with distinction)','MBChB (with distinction)','CURRENT'),
('MBChB /MBBS','MBChB /MBBS','CURRENT'),
('MBChB 1996','MBChB 1996','CURRENT'),
('MBChB Bachelor of Medicine and','MBChB Bachelor of Medicine and','CURRENT'),
('MBChB Bachelor of Medicine and Bachelor of Surgery','MBChB Bachelor of Medicine and Bachelor of Surgery','CURRENT'),
('MBChB Bachelor of Medicine and Surgery','MBChB Bachelor of Medicine and Surgery','CURRENT'),
('MBChB BAO','MBChB BAO','CURRENT'),
('MBChB DA MRCGP','MBChB DA MRCGP','CURRENT'),
('MBChB DFFP','MBChB DFFP','CURRENT'),
('MBChB DGM MRCGP','MBChB DGM MRCGP','CURRENT'),
('MBChB DRCOG','MBChB DRCOG','CURRENT'),
('MBChB DRCOG DFFP','MBChB DRCOG DFFP','CURRENT'),
('MBChB DRCOG DFFP MRCGP','MBChB DRCOG DFFP MRCGP','CURRENT'),
('MBChB DRCOG DFFP MRCGP DCH','MBChB DRCOG DFFP MRCGP DCH','CURRENT'),
('MBChB DRCOG FPCERT MRCGP','MBChB DRCOG FPCERT MRCGP','CURRENT'),
('MBchB DRCOG MRCGGP','MBchB DRCOG MRCGGP','CURRENT'),
('MBChB DRCOG MRCGP','MBChB DRCOG MRCGP','CURRENT'),
('MBChB DRCOG, DCH','MBChB DRCOG, DCH','CURRENT'),
('MBChB FRCS (Ed) DRCOG MRCGP','MBChB FRCS (Ed) DRCOG MRCGP','CURRENT'),
('MBChB LMCC MSCGP MRCGP','MBChB LMCC MSCGP MRCGP','CURRENT'),
('MBChB Medicine (with pre-medical year)','MBChB Medicine (with pre-medical year)','CURRENT'),
('MBChB MRCGP','MBChB MRCGP','CURRENT'),
('MBChB MRCGP DA','MBChB MRCGP DA','CURRENT'),
('MBChB MRCGP DCH','MBChB MRCGP DCH','CURRENT'),
('MBChB MRCGP DFFP DCCH','MBChB MRCGP DFFP DCCH','CURRENT'),
('MBChB MRCGP DRCOG','MBChB MRCGP DRCOG','CURRENT'),
('MBChB MRCGP DRCOG Fellow FPP','MBChB MRCGP DRCOG Fellow FPP','CURRENT'),
('MBChB MRCGP DROG','MBChB MRCGP DROG','CURRENT'),
('MBChB MRCGP FRCOG','MBChB MRCGP FRCOG','CURRENT'),
('MBChB MRCGP FRCSed','MBChB MRCGP FRCSed','CURRENT'),
('MBChB MRCGP MSc Sports Medicin','MBChB MRCGP MSc Sports Medicin','CURRENT'),
('MBChB MRCP MRCGP','MBChB MRCP MRCGP','CURRENT'),
('MBChB MRCP MRCGP DCH','MBChB MRCP MRCGP DCH','CURRENT'),
('MBChB MRCS','MBChB MRCS','CURRENT'),
('MBChB RCGP DFFP','MBChB RCGP DFFP','CURRENT'),
('MBChB(Hons)','MBChB(Hons)','CURRENT'),
('MBChB(Hons)  BSc(Hon','MBChB(Hons)  BSc(Hon','CURRENT'),
('MBChB, BSc (Hons), DRCOG, DCH,','MBChB, BSc (Hons), DRCOG, DCH,','CURRENT'),
('MBChB, DRCOG, DFFP, MRCGP','MBChB, DRCOG, DFFP, MRCGP','CURRENT'),
('MBChB, DRCOG, DHC, MRCGP','MBChB, DRCOG, DHC, MRCGP','CURRENT'),
('MBChB, DRCOG, FPC','MBChB, DRCOG, FPC','CURRENT'),
('MBChB, DRPG, MRCGP','MBChB, DRPG, MRCGP','CURRENT'),
('MBChB, MRCGP','MBChB, MRCGP','CURRENT'),
('MBChB, MRCGP, DCH, DGM, DRCOG,','MBChB, MRCGP, DCH, DGM, DRCOG,','CURRENT'),
('MBChB, MRCGP, DFFP','MBChB, MRCGP, DFFP','CURRENT'),
('MBChB, MRCGP, DGM','MBChB, MRCGP, DGM','CURRENT'),
('MBChB, MRCGP, DRCOG, DA (UK),','MBChB, MRCGP, DRCOG, DA (UK),','CURRENT'),
('MBChB, MRCGP, DRCOG, DFFP','MBChB, MRCGP, DRCOG, DFFP','CURRENT'),
('MBChB, MRCGP, DRCOG,DFFP','MBChB, MRCGP, DRCOG,DFFP','CURRENT'),
('MBChB, MRCGP, DRLOG, DFFP, MSc','MBChB, MRCGP, DRLOG, DFFP, MSc','CURRENT'),
('MBChB,MRCGP,DCH','MBChB,MRCGP,DCH','CURRENT'),
('MBChB,MRCGP,DRCOG,FP Cert','MBChB,MRCGP,DRCOG,FP Cert','CURRENT'),
('MBChB,MRCGP,DRCOG,MEHom','MBChB,MRCGP,DRCOG,MEHom','CURRENT'),
('MBChB,MRCGP,FP Cert','MBChB,MRCGP,FP Cert','CURRENT'),
('MBChB,MRCGP,PGD:pENT','MBChB,MRCGP,PGD:pENT','CURRENT'),
('MBChB.','MBChB.','CURRENT'),
('MBChB., BSc (HONS)','MBChB., BSc (HONS)','CURRENT'),
('MBChB/MED','MBChB/MED','CURRENT'),
('MBChB; BSc (Hons) MR','MBChB; BSc (Hons) MR','CURRENT'),
('MBChB; MRCGP; DRCOG; FP Cert','MBChB; MRCGP; DRCOG; FP Cert','CURRENT'),
('MBChBHon','MBChBHon','CURRENT'),
('MBChD','MBChD','CURRENT'),
('MBChM MRCGP DRCOG','MBChM MRCGP DRCOG','CURRENT'),
('MBCRB FRCGP DRCOG','MBCRB FRCGP DRCOG','CURRENT'),
('MBMCh','MBMCh','CURRENT'),
('MBMch DRCOG MRCGP','MBMch DRCOG MRCGP','CURRENT'),
('MBMS','MBMS','CURRENT'),
('MBS','MBS','CURRENT'),
('MCB','MCB','CURRENT'),
('MCEM','MCEM','CURRENT'),
('MCEM A','MCEM A','CURRENT'),
('MCEM Part A','MCEM Part A','CURRENT'),
('MCEM Part B','MCEM Part B','CURRENT'),
('MCEM Part C','MCEM Part C','CURRENT'),
('MCh','MCh','CURRENT'),
('MCh (cardiothoracic)','MCh (cardiothoracic)','CURRENT'),
('MCh (Orth)','MCh (Orth)','CURRENT'),
('Mch Ms','Mch Ms','CURRENT'),
('MCh Orth','MCh Orth','CURRENT'),
('MCLIN DENT','MCLIN DENT','CURRENT'),
('MClinDent','MClinDent','CURRENT'),
('MClinDent in Paediatric Dentistry','MClinDent in Paediatric Dentistry','CURRENT'),
('mcps','mcps','CURRENT'),
('MCPS Pak','MCPS Pak','CURRENT'),
('MD','MD','CURRENT'),
('MD (Anaesthesia)','MD (Anaesthesia)','CURRENT'),
('MD (Berlin)','MD (Berlin)','CURRENT'),
('MD (Hons)','MD (Hons)','CURRENT'),
('MD (Med)','MD (Med)','CURRENT'),
('MD (Obst & Gynae)','MD (Obst & Gynae)','CURRENT'),
('MD (paediatrics)','MD (paediatrics)','CURRENT'),
('MD (Path)','MD (Path)','CURRENT'),
('MD (Phillipines)','MD (Phillipines)','CURRENT'),
('MD (Psychiatry)','MD (Psychiatry)','CURRENT'),
('MD (psychological medicine)','MD (psychological medicine)','CURRENT'),
('MD (radio-diagnosis)','MD (radio-diagnosis)','CURRENT'),
('MD cum laude','MD cum laude','CURRENT'),
('Md DIP','Md DIP','CURRENT'),
('MD Doctor of Medicine','MD Doctor of Medicine','CURRENT'),
('MD in   MD in Medicine','MD in   MD in Medicine','CURRENT'),
('MD in Obstetrics and Gynaecology','MD in Obstetrics and Gynaecology','CURRENT'),
('MD in paediatrics  MD in Medicine','MD in paediatrics  MD in Medicine','CURRENT'),
('MD Paediatrics','MD Paediatrics','CURRENT'),
('MD Thesis','MD Thesis','CURRENT'),
('MD;LMSSA','MD;LMSSA','CURRENT'),
('MDDr','MDDr','CURRENT'),
('MDentSci','MDentSci','CURRENT'),
('MDS','MDS','CURRENT'),
('MED DOC','MED DOC','CURRENT'),
('Med Exam','Med Exam','CURRENT'),
('Med Univ','Med Univ','CURRENT'),
('MedDegre','MedDegre','CURRENT'),
('Medic','Medic','CURRENT'),
('Medic Diploma','Medic Diploma','CURRENT'),
('Medical','Medical','CURRENT'),
('Medical Degree','Medical Degree','CURRENT'),
('Medical Degree - MBChB','Medical Degree - MBChB','CURRENT'),
('Medical Degree (Australia)','Medical Degree (Australia)','CURRENT'),
('Medical Degree (Cairo)','Medical Degree (Cairo)','CURRENT'),
('Medical Degree (Dutch)','Medical Degree (Dutch)','CURRENT'),
('Medical Degree (Geneeskunde)','Medical Degree (Geneeskunde)','CURRENT'),
('Medical Degree (Spain)','Medical Degree (Spain)','CURRENT'),
('Medical Directorate`','Medical Directorate`','CURRENT'),
('Medical State Exam (Germany)','Medical State Exam (Germany)','CURRENT'),
('medical state examination','medical state examination','CURRENT'),
('Medicine - MBChB','Medicine - MBChB','CURRENT'),
('Medicine and Dentistry','Medicine and Dentistry','CURRENT'),
('Medicine in Developed Countries','Medicine in Developed Countries','CURRENT'),
('medicine MD','medicine MD','CURRENT'),
('Medico','Medico','CURRENT'),
('Medico Chirujano','Medico Chirujano','CURRENT'),
('MEDSG','MEDSG','CURRENT'),
('Member of the Institute of Psychotherapy','Member of the Institute of Psychotherapy','CURRENT'),
('Membership Examination in Anaesthesia','Membership Examination in Anaesthesia','CURRENT'),
('Mestrado Integrado em Medicina','Mestrado Integrado em Medicina','CURRENT'),
('MFAEM','MFAEM','CURRENT'),
('MFDS','MFDS','CURRENT'),
('MFDS ( Part A)','MFDS ( Part A)','CURRENT'),
('MFDS (A)','MFDS (A)','CURRENT'),
('MFDS (Part B)','MFDS (Part B)','CURRENT'),
('MFDS (Part C)','MFDS (Part C)','CURRENT'),
('MFDSRCS','MFDSRCS','CURRENT'),
('MFFP PART 1','MFFP PART 1','CURRENT'),
('MFFP Part I','MFFP Part I','CURRENT'),
('MFGDP','MFGDP','CURRENT'),
('MFPH','MFPH','CURRENT'),
('MFPHM Part B','MFPHM Part B','CURRENT'),
('MFPHM Part I','MFPHM Part I','CURRENT'),
('MFPHM Part II','MFPHM Part II','CURRENT'),
('MIBiol','MIBiol','CURRENT'),
('MICGP','MICGP','CURRENT'),
('Minor Surgery','Minor Surgery','CURRENT'),
('MJDF','MJDF','CURRENT'),
('MJDF / MFDS or FDS RCS or equivalent','MJDF / MFDS or FDS RCS or equivalent','CURRENT'),
('Mjek i  Perg','Mjek i  Perg','CURRENT'),
('Mjek I perg','Mjek I perg','CURRENT'),
('Mjek i Përgjithshëm','Mjek i Përgjithshëm','CURRENT'),
('MM Med Sci FRSM(EQUIVALENT M','MM Med Sci FRSM(EQUIVALENT M','CURRENT'),
('MMBCH','MMBCH','CURRENT'),
('Mmed (Paediatrics)','Mmed (Paediatrics)','CURRENT'),
('MMEDSc','MMEDSc','CURRENT'),
('MMedSci','MMedSci','CURRENT'),
('MMedSci (Clinical Psychiatry)','MMedSci (Clinical Psychiatry)','CURRENT'),
('MMMBChB','MMMBChB','CURRENT'),
('Morth (Part-I)','Morth (Part-I)','CURRENT'),
('Morth Dent','Morth Dent','CURRENT'),
('MOrthRCPS','MOrthRCPS','CURRENT'),
('MOrthRCS','MOrthRCS','CURRENT'),
('Motivational Interviewing Training','Motivational Interviewing Training','CURRENT'),
('MPaedDent or equivalent','MPaedDent or equivalent','CURRENT'),
('MPH & TM','MPH & TM','CURRENT'),
('MPharm','MPharm','CURRENT'),
('MR CP','MR CP','CURRENT'),
('MR CS','MR CS','CURRENT'),
('MR.BCHIR','MR.BCHIR','CURRENT'),
('MRC Path','MRC Path','CURRENT'),
('MRC PCH','MRC PCH','CURRENT'),
('MRCGP','MRCGP','CURRENT'),
('MRCGP AFRCSI DRCOG','MRCGP AFRCSI DRCOG','CURRENT'),
('MRCGP BSc (Med Sci) MBChB','MRCGP BSc (Med Sci) MBChB','CURRENT'),
('MRCGP DFFP','MRCGP DFFP','CURRENT'),
('MRCGP DFFP Dip ENT','MRCGP DFFP Dip ENT','CURRENT'),
('MRCGP DRCOG','MRCGP DRCOG','CURRENT'),
('MRCGP DRCOG MB ChB','MRCGP DRCOG MB ChB','CURRENT'),
('MRCGP MBBS BSc Psycholgy','MRCGP MBBS BSc Psycholgy','CURRENT'),
('MRCGP MBBS DFFP FRCS','MRCGP MBBS DFFP FRCS','CURRENT'),
('MRCGP, BM BS Bmed Sci','MRCGP, BM BS Bmed Sci','CURRENT'),
('MRCGP, DRCOG, DFFP','MRCGP, DRCOG, DFFP','CURRENT'),
('MRCGP, FPC','MRCGP, FPC','CURRENT'),
('MRCGP, MBChB Medicine, RCGP','MRCGP, MBChB Medicine, RCGP','CURRENT'),
('MRCGP,DCH,DPD,DFFP,BM','MRCGP,DCH,DPD,DFFP,BM','CURRENT'),
('MRCHB','MRCHB','CURRENT'),
('MRCOG (1995)','MRCOG (1995)','CURRENT'),
('MRCOG II','MRCOG II','CURRENT'),
('MRCOG Part 1','MRCOG Part 1','CURRENT'),
('MRCOG Part 2','MRCOG Part 2','CURRENT'),
('MRCOG Part I','MRCOG Part I','CURRENT'),
('MRCOG Part II','MRCOG Part II','CURRENT'),
('MRCOhth','MRCOhth','CURRENT'),
('MRCOP','MRCOP','CURRENT'),
('MRCOphth','MRCOphth','CURRENT'),
('MRCOphth II','MRCOphth II','CURRENT'),
('MRCOphth III','MRCOphth III','CURRENT'),
('MRCOphth Part 2','MRCOphth Part 2','CURRENT'),
('MRCOphth Part II','MRCOphth Part II','CURRENT'),
('MRCP 1/FRCR','MRCP 1/FRCR','CURRENT'),
('MRCP 2','MRCP 2','CURRENT'),
('MRCP Dip GUM','MRCP Dip GUM','CURRENT'),
('MRCP I','MRCP I','CURRENT'),
('MRCP I&II','MRCP I&II','CURRENT'),
('MRCP II','MRCP II','CURRENT'),
('MRCP II Written','MRCP II Written','CURRENT'),
('MRCP Paces','MRCP Paces','CURRENT'),
('MRCP Part 1','MRCP Part 1','CURRENT'),
('MRCP Part 2','MRCP Part 2','CURRENT'),
('MRCP Part 2 PACES','MRCP Part 2 PACES','CURRENT'),
('MRCP Part 2 Written','MRCP Part 2 Written','CURRENT'),
('MRCP Part I','MRCP Part I','CURRENT'),
('MRCP Part II','MRCP Part II','CURRENT'),
('MRCP Path Part 2','MRCP Path Part 2','CURRENT'),
('MRCP PT1','MRCP PT1','CURRENT'),
('MRCP(Paeds)','MRCP(Paeds)','CURRENT'),
('MRCP(UK)','MRCP(UK)','CURRENT'),
('MRCP, DCH, DRCOG, MRCGP','MRCP, DCH, DRCOG, MRCGP','CURRENT'),
('MRCP, MRCGP, FRCGP','MRCP, MRCGP, FRCGP','CURRENT'),
('MRCP/FRCR','MRCP/FRCR','CURRENT'),
('MRCPATH (Parts 1&2)','MRCPATH (Parts 1&2)','CURRENT'),
('MRCPath I','MRCPath I','CURRENT'),
('MRCPath II','MRCPath II','CURRENT'),
('MRCPath Part 1','MRCPath Part 1','CURRENT'),
('MRCPath Part 2','MRCPath Part 2','CURRENT'),
('MRCPCH - Applied Knowledge in Practice Exam','MRCPCH - Applied Knowledge in Practice Exam','CURRENT'),
('MRCPCH - Foundation of Practice Exam','MRCPCH - Foundation of Practice Exam','CURRENT'),
('MRCPCH - Theory and Science Exam','MRCPCH - Theory and Science Exam','CURRENT'),
('MRCPCH Clinical','MRCPCH Clinical','CURRENT'),
('MRCPCH Part 1','MRCPCH Part 1','CURRENT'),
('MRCPCH Part 1a','MRCPCH Part 1a','CURRENT'),
('MRCPCH Part 1b','MRCPCH Part 1b','CURRENT'),
('MRCPCH Part 2 (Paper 1)','MRCPCH Part 2 (Paper 1)','CURRENT'),
('MRCPCH Part 2 (Paper)','MRCPCH Part 2 (Paper)','CURRENT'),
('MRCPhysh','MRCPhysh','CURRENT'),
('MRCPsych 1','MRCPsych 1','CURRENT'),
('MRCPsych CASC','MRCPsych CASC','CURRENT'),
('MRCPsych Paper 1','MRCPsych Paper 1','CURRENT'),
('MRCPsych Paper 2','MRCPsych Paper 2','CURRENT'),
('MRCPsych Paper 3','MRCPsych Paper 3','CURRENT'),
('MRCPsych Paper A','MRCPsych Paper A','CURRENT'),
('MRCPsych Paper B','MRCPsych Paper B','CURRENT'),
('MRCS -  Part 1','MRCS -  Part 1','CURRENT'),
('mrcs  Part 1','mrcs  Part 1','CURRENT'),
('MRCS  Part 1,2,3','MRCS  Part 1,2,3','CURRENT'),
('MRCS - Part 2','MRCS - Part 2','CURRENT'),
('MRCS - Part 3','MRCS - Part 3','CURRENT'),
('MRCS  Part I','MRCS  Part I','CURRENT'),
('MRCS  Parts 1 and 2','MRCS  Parts 1 and 2','CURRENT'),
('MRCS (Ed)','MRCS (Ed)','CURRENT'),
('MRCS (Edinburgh)','MRCS (Edinburgh)','CURRENT'),
('MRCS (ENG)','MRCS (ENG)','CURRENT'),
('MRCS (Part II)','MRCS (Part II)','CURRENT'),
('MRCS (RCS, London)','MRCS (RCS, London)','CURRENT'),
('MRCS Ed  (Ophthalm)','MRCS Ed  (Ophthalm)','CURRENT'),
('MRCS Ed (A&E)','MRCS Ed (A&E)','CURRENT'),
('MRCS ENG','MRCS ENG','CURRENT'),
('MRCS Eng LRCP','MRCS Eng LRCP','CURRENT'),
('MRCS I','MRCS I','CURRENT'),
('MRCS Part 1','MRCS Part 1','CURRENT'),
('MRCS part 123','MRCS part 123','CURRENT'),
('MRCS Part 2','MRCS Part 2','CURRENT'),
('MRCS Part 3','MRCS Part 3','CURRENT'),
('MRCS Part A','MRCS Part A','CURRENT'),
('MRCS Part B','MRCS Part B','CURRENT'),
('MRCS written','MRCS written','CURRENT'),
('MRCS(England)','MRCS(England)','CURRENT'),
('MRCS, LRcP, DROG, FRCGP','MRCS, LRcP, DROG, FRCGP','CURRENT'),
('MRCS1','MRCS1','CURRENT'),
('MRCS2','MRCS2','CURRENT'),
('MRCUP','MRCUP','CURRENT'),
('MRD','MRD','CURRENT'),
('MRGP MBChB','MRGP MBChB','CURRENT'),
('MRSC(Ed)','MRSC(Ed)','CURRENT'),
('MS (Orth)','MS (Orth)','CURRENT'),
('MS GENERAL SURGERY, MBBS, FPC','MS GENERAL SURGERY, MBBS, FPC','CURRENT'),
('MS GenSurg','MS GenSurg','CURRENT'),
('MS Ophthalmology','MS Ophthalmology','CURRENT'),
('MS Orth','MS Orth','CURRENT'),
('MSc','MSc','CURRENT'),
('MSC (Biochemistry)','MSC (Biochemistry)','CURRENT'),
('MSc (Clinical Immunology)','MSc (Clinical Immunology)','CURRENT'),
('MSc (Community Medicine)','MSc (Community Medicine)','CURRENT'),
('MSc (Epidemiology)','MSc (Epidemiology)','CURRENT'),
('MSC (General Practice)','MSC (General Practice)','CURRENT'),
('MSc (Med Sci)','MSc (Med Sci)','CURRENT'),
('MSC (Neurophysiology)','MSC (Neurophysiology)','CURRENT'),
('MSc (Obstetrics & Gynaecology)','MSc (Obstetrics & Gynaecology)','CURRENT'),
('MSc (Occupational Medicine)','MSc (Occupational Medicine)','CURRENT'),
('MSc (Orth)','MSc (Orth)','CURRENT'),
('MSC (Orthopaedics)','MSC (Orthopaedics)','CURRENT'),
('MSc (Periodontics)','MSc (Periodontics)','CURRENT'),
('MSc (Rheumatology)','MSc (Rheumatology)','CURRENT'),
('MSc Audiology','MSc Audiology','CURRENT'),
('MSc developing country psychiatry','MSc developing country psychiatry','CURRENT'),
('MSC Epilepsy','MSC Epilepsy','CURRENT'),
('MSc Fac of Med','MSc Fac of Med','CURRENT'),
('MSc Faculty of Medicine','MSc Faculty of Medicine','CURRENT'),
('MSc Gerontology','MSc Gerontology','CURRENT'),
('MSc Histopathology','MSc Histopathology','CURRENT'),
('MSc in Epidemiology and Biostatistics','MSc in Epidemiology and Biostatistics','CURRENT'),
('MSc in PH','MSc in PH','CURRENT'),
('MSc MClin Dent','MSc MClin Dent','CURRENT'),
('MSc Medicine Engineering','MSc Medicine Engineering','CURRENT'),
('MSc Molecular Microbiology','MSc Molecular Microbiology','CURRENT'),
('MSc Psychiatry','MSc Psychiatry','CURRENT'),
('MSc Public Health','MSc Public Health','CURRENT'),
('Msc Trauma','Msc Trauma','CURRENT'),
('MSc(Orth)','MSc(Orth)','CURRENT'),
('MSc, MClin Dent','MSc, MClin Dent','CURRENT'),
('MSc. Community Paediatrics','MSc. Community Paediatrics','CURRENT'),
('MScMB','MScMB','CURRENT'),
('MScUB, MRCGP','MScUB, MRCGP','CURRENT'),
('MSDS','MSDS','CURRENT'),
('MUDr','MUDr','CURRENT'),
('MUDr (Dr in General Medicine)','MUDr (Dr in General Medicine)','CURRENT'),
('MUDr (Hons)','MUDr (Hons)','CURRENT'),
('MVChB MRCGP DFFP DRCOG','MVChB MRCGP DFFP DRCOG','CURRENT'),
('N/A','N/A','CURRENT'),
('Neurorehabilitation','Neurorehabilitation','CURRENT'),
('NLS','NLS','CURRENT'),
('Obstetrics and Gynaecology','Obstetrics and Gynaecology','CURRENT'),
('Oral Medicine & Periodontology','Oral Medicine & Periodontology','CURRENT'),
('Ordinary National Diploma in Business Studies','Ordinary National Diploma in Business Studies','CURRENT'),
('Other','Other','CURRENT'),
('Other - BM BCh','Other - BM BCh','CURRENT'),
('Other - M.D','Other - M.D','CURRENT'),
('Other - MBBChir','Other - MBBChir','CURRENT'),
('Other - MD','Other - MD','CURRENT'),
('Other - MD Innsbruck','Other - MD Innsbruck','CURRENT'),
('Other - State Exam Med Uni','Other - State Exam Med Uni','CURRENT'),
('Other - state examination','Other - state examination','CURRENT'),
('Other:  State Examination','Other:  State Examination','CURRENT'),
('Other: Lekarz medycyny','Other: Lekarz medycyny','CURRENT'),
('Other: please specify','Other: please specify','CURRENT'),
('PACES','PACES','CURRENT'),
('Part A MFPH','Part A MFPH','CURRENT'),
('Part B MFPH','Part B MFPH','CURRENT'),
('Part I DFPHM','Part I DFPHM','CURRENT'),
('PCME','PCME','CURRENT'),
('PG Certificate in Computer Programming','PG Certificate in Computer Programming','CURRENT'),
('PG Certificate in Education','PG Certificate in Education','CURRENT'),
('PG Certificate in Management of Allergic Diseases','PG Certificate in Management of Allergic Diseases','CURRENT'),
('PG Certificate in Managing Health Services','PG Certificate in Managing Health Services','CURRENT'),
('PG Degree in General Surgery','PG Degree in General Surgery','CURRENT'),
('PG Dip Clinical Ultrasound (Distinction)','PG Dip Clinical Ultrasound (Distinction)','CURRENT'),
('PG DipEd','PG DipEd','CURRENT'),
('PG Diploma In Computer Applications','PG Diploma In Computer Applications','CURRENT'),
('PGC Palliative Care','PGC Palliative Care','CURRENT'),
('PGCE, BSc(Hons), RGN, MSc','PGCE, BSc(Hons), RGN, MSc','CURRENT'),
('PGCHE','PGCHE','CURRENT'),
('PGEC','PGEC','CURRENT'),
('PHD in Medical Science','PHD in Medical Science','CURRENT'),
('Physician','Physician','CURRENT'),
('Physiology','Physiology','CURRENT'),
('Physiotherapy BSc (Hons) ','Physiotherapy BSc (Hons) ','CURRENT'),
('PLAB Part 1','PLAB Part 1','CURRENT'),
('PLAB Part 1 & 2','PLAB Part 1 & 2','CURRENT'),
('PLAB Part 2','PLAB Part 2','CURRENT'),
('pls','pls','CURRENT'),
('POPUMET','POPUMET','CURRENT'),
('POPUMET (Radiation Certificate)','POPUMET (Radiation Certificate)','CURRENT'),
('Postgraduate Certificate in Medical Education','Postgraduate Certificate in Medical Education','CURRENT'),
('Postgraduate Certificate of Medical Education','Postgraduate Certificate of Medical Education','CURRENT'),
('Postgraduate Diploma in Clinical Psychiatry','Postgraduate Diploma in Clinical Psychiatry','CURRENT'),
('Postgraduate Diploma in Dermatology & GU Medicine','Postgraduate Diploma in Dermatology & GU Medicine','CURRENT'),
('Pre-medical Science','Pre-medical Science','CURRENT'),
('Primary Fellowship','Primary Fellowship','CURRENT'),
('Primary Fellowship, Faculty of Paediatrics','Primary Fellowship, Faculty of Paediatrics','CURRENT'),
('Principles of Surgery-RCSCanada','Principles of Surgery-RCSCanada','CURRENT'),
('Psychology','Psychology','CURRENT'),
('Psychology and Psychaitry','Psychology and Psychaitry','CURRENT'),
('Psycotherapy','Psycotherapy','CURRENT'),
('Ptychio Iatrikes','Ptychio Iatrikes','CURRENT'),
('Ptychio latrikes (Athens)','Ptychio latrikes (Athens)','CURRENT'),
('Ptychion Iatrikes','Ptychion Iatrikes','CURRENT'),
('RCOE','RCOE','CURRENT'),
('RCOG','RCOG','CURRENT'),
('RCPS','RCPS','CURRENT'),
('RCPS (Rest. Dent.)','RCPS (Rest. Dent.)','CURRENT'),
('RCR','RCR','CURRENT'),
('RCS Edinburgh','RCS Edinburgh','CURRENT'),
('RCS Eng','RCS Eng','CURRENT'),
('RCS I','RCS I','CURRENT'),
('Registered General Nurse (Germany)','Registered General Nurse (Germany)','CURRENT'),
('Registered General Nursing','Registered General Nursing','CURRENT'),
('Rest Dent','Rest Dent','CURRENT'),
('Rhuematology Specialty Certificate Exam','Rhuematology Specialty Certificate Exam','CURRENT'),
('RSC1','RSC1','CURRENT'),
('S. Thames Certificate in Teaching (Cons)','S. Thames Certificate in Teaching (Cons)','CURRENT'),
('SCE Geriatric Medicine','SCE Geriatric Medicine','CURRENT'),
('Senior Medical Officer','Senior Medical Officer','CURRENT'),
('SI','SI','CURRENT'),
('Specialist Degree in Vascular Surgery','Specialist Degree in Vascular Surgery','CURRENT'),
('Specialist Urologist','Specialist Urologist','CURRENT'),
('Specilisation Infectious Diseases','Specilisation Infectious Diseases','CURRENT'),
('Staatsen','Staatsen','CURRENT'),
('Staatsexamen Medizin','Staatsexamen Medizin','CURRENT'),
('State DMS','State DMS','CURRENT'),
('State Exam DMS','State Exam DMS','CURRENT'),
('State Exam Med','State Exam Med','CURRENT'),
('State Exam Med  - Germany','State Exam Med  - Germany','CURRENT'),
('State Exam Med 2003','State Exam Med 2003','CURRENT'),
('State Exam. Med','State Exam. Med','CURRENT'),
('Statutory Exam (Dentistry)','Statutory Exam (Dentistry)','CURRENT'),
('Statutory Exam (GDC)','Statutory Exam (GDC)','CURRENT'),
('Studies of Medicine','Studies of Medicine','CURRENT'),
('Swiss Federal Diploma','Swiss Federal Diploma','CURRENT'),
('SYNTEX AWARD','SYNTEX AWARD','CURRENT'),
('TBA','TBA','CURRENT'),
('Theoretical Course of Family Planning','Theoretical Course of Family Planning','CURRENT'),
('Tip Doktoru','Tip Doktoru','CURRENT'),
('TLMC - MADRID','TLMC - MADRID','CURRENT'),
('TRACP, The Royal Australian College of Physicians','TRACP, The Royal Australian College of Physicians','CURRENT'),
('Tropical Surgery','Tropical Surgery','CURRENT'),
('TSEM','TSEM','CURRENT'),
('University Certification of Medical Doctor','University Certification of Medical Doctor','CURRENT'),
('USMLE I','USMLE I','CURRENT'),
('USMLE II','USMLE II','CURRENT'),
('USMLE III','USMLE III','CURRENT'),
('VRAC','VRAC','CURRENT'),
('Vrach','Vrach','CURRENT'),
('vrash','vrash','CURRENT'),
('Zeugnis über die Ärztliche Prüfung (State Exam Ct)','Zeugnis über die Ärztliche Prüfung (State Exam Ct)','CURRENT');

