INSERT INTO Nationality(countryNumber,nationality) SELECT 'Afghan','Afghan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Afghan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Albanian','Albanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Albanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Algerian','Algerian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Algerian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'American','American' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='American') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'American Samoan','American Samoan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='American Samoan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Andorran','Andorran' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Andorran') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Angolan','Angolan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Angolan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Anguillan','Anguillan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Anguillan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Antiguan','Antiguan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Antiguan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Argentine','Argentine' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Argentine') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Armenian','Armenian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Armenian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Aruban','Aruban' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Aruban') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Australian','Australian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Australian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Austrian','Austrian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Austrian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Azerbaijani','Azerbaijani' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Azerbaijani') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bahamian','Bahamian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bahamian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bahraini','Bahraini' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bahraini') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bangladeshi','Bangladeshi' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bangladeshi') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Barbadian','Barbadian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Barbadian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Barbudan','Barbudan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Barbudan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Basotho','Basotho' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Basotho') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Belarusian','Belarusian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Belarusian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Belgian','Belgian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Belgian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Belizean','Belizean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Belizean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Beninese','Beninese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Beninese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bermudian','Bermudian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bermudian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bhutanese','Bhutanese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bhutanese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bolivian','Bolivian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bolivian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bosnian','Bosnian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bosnian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Brazilian','Brazilian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Brazilian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'British','British' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='British') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'British Virgin Islander','British Virgin Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='British Virgin Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bruneian','Bruneian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bruneian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Bulgarian','Bulgarian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Bulgarian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Burkinabe','Burkinabe' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Burkinabe') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Burmese','Burmese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Burmese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Burundi','Burundi' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Burundi') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Cambodian','Cambodian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Cambodian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Cameroonian','Cameroonian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Cameroonian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Canadian','Canadian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Canadian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Cape Verdean','Cape Verdean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Cape Verdean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Caymanian','Caymanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Caymanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Central African','Central African' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Central African') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Chadian','Chadian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Chadian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Channel Islander','Channel Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Channel Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Chilean','Chilean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Chilean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Chinese','Chinese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Chinese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Christmas Islander','Christmas Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Christmas Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Chuukese','Chuukese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Chuukese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Cocos Islander','Cocos Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Cocos Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Colombian','Colombian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Colombian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Comoran','Comoran' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Comoran') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Congolese','Congolese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Congolese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Cook Islander','Cook Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Cook Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Costa Rican','Costa Rican' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Costa Rican') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Croatian','Croatian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Croatian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Cuban','Cuban' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Cuban') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Cypriot','Cypriot' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Cypriot') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Czech','Czech' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Czech') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Danish','Danish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Danish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Djiboutian','Djiboutian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Djiboutian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Dominican','Dominican' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Dominican') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Dutch','Dutch' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Dutch') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Dutch Antillean','Dutch Antillean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Dutch Antillean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Ecuadorian','Ecuadorian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Ecuadorian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Egyptian','Egyptian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Egyptian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Emirati','Emirati' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Emirati') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'English','English' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='English') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Equatorial Guinean','Equatorial Guinean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Equatorial Guinean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Eritrean','Eritrean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Eritrean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Estonian','Estonian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Estonian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Ethiopian','Ethiopian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Ethiopian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Falkland Islander','Falkland Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Falkland Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Faroese','Faroese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Faroese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Fijian','Fijian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Fijian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Finnish','Finnish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Finnish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'French','French' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='French') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'French Guianese','French Guianese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='French Guianese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'French Polynesian','French Polynesian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='French Polynesian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Gabonese','Gabonese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Gabonese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Gambian','Gambian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Gambian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Georgian','Georgian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Georgian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'German','German' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='German') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Ghanaian','Ghanaian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Ghanaian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Gibraltar','Gibraltar' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Gibraltar') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Greek','Greek' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Greek') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Greenlandic','Greenlandic' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Greenlandic') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Grenadian','Grenadian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Grenadian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Guadeloupe','Guadeloupe' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Guadeloupe') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Guamanian','Guamanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Guamanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Guatemalan','Guatemalan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Guatemalan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Guinean','Guinean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Guinean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Guyanese','Guyanese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Guyanese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Haitian','Haitian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Haitian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Honduran','Honduran' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Honduran') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Hong Kong (British/Chinese)','Hong Kong (British/Chinese)' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Hong Kong (British/Chinese)') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Hungarian','Hungarian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Hungarian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Icelandic','Icelandic' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Icelandic') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'I-Kiribati','I-Kiribati' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='I-Kiribati') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Indian','Indian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Indian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Indonesian','Indonesian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Indonesian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Iranian','Iranian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Iranian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Iraqi','Iraqi' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Iraqi') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Irish','Irish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Irish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Israeli','Israeli' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Israeli') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Italian','Italian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Italian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Ivorian','Ivorian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Ivorian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Jamaican','Jamaican' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Jamaican') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Japanese','Japanese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Japanese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Jordanian','Jordanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Jordanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Kazakhstani','Kazakhstani' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Kazakhstani') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Kenyan','Kenyan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Kenyan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Kittitian','Kittitian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Kittitian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Korean','Korean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Korean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Korean','Korean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Korean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Kosrae','Kosrae' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Kosrae') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Kuwaiti','Kuwaiti' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Kuwaiti') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Kyrgyzstani','Kyrgyzstani' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Kyrgyzstani') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Laotian','Laotian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Laotian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Latin American','Latin American' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Latin American') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Latvian','Latvian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Latvian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Lebanese','Lebanese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Lebanese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Liberian','Liberian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Liberian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Libyan','Libyan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Libyan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Liechtenstein','Liechtenstein' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Liechtenstein') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Lithuanian','Lithuanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Lithuanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Luxembourg','Luxembourg' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Luxembourg') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Macedonian','Macedonian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Macedonian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Mahoran','Mahoran' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Mahoran') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Malagasy','Malagasy' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Malagasy') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Malawian','Malawian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Malawian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Malaysian','Malaysian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Malaysian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Maldivian','Maldivian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Maldivian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Malian','Malian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Malian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Maltese','Maltese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Maltese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Manx','Manx' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Manx') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Marshallese','Marshallese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Marshallese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Martiniquais','Martiniquais' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Martiniquais') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Mauritanian','Mauritanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Mauritanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Mauritian','Mauritian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Mauritian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Mexican','Mexican' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Mexican') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Micronesian','Micronesian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Micronesian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Moldovan','Moldovan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Moldovan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Monegasque','Monegasque' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Monegasque') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Mongolian','Mongolian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Mongolian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Montenegrin','Montenegrin' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Montenegrin') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Montserratian','Montserratian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Montserratian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Moroccan','Moroccan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Moroccan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Motswana','Motswana' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Motswana') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Mozambican','Mozambican' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Mozambican') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Namibian','Namibian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Namibian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Nauruan','Nauruan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Nauruan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Nepalese','Nepalese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Nepalese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'New Caledonian','New Caledonian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='New Caledonian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'New Zealand','New Zealand' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='New Zealand') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Nicaraguan','Nicaraguan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Nicaraguan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Nigerian','Nigerian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Nigerian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Nigerien','Nigerien' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Nigerien') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Niuean','Niuean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Niuean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Ni-Vanuatu','Ni-Vanuatu' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Ni-Vanuatu') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Norfolk Islander','Norfolk Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Norfolk Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'North Korean ','North Korean ' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='North Korean ') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Northern Irish','Northern Irish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Northern Irish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Norwegian','Norwegian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Norwegian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Norwegian (Old)','Norwegian (Old)' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Norwegian (Old)') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Omani','Omani' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Omani') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Pakistani','Pakistani' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Pakistani') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Palauan','Palauan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Palauan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Palestinian','Palestinian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Palestinian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Panamanian','Panamanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Panamanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Papua New Guinean','Papua New Guinean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Papua New Guinean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Paraguayan','Paraguayan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Paraguayan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Peruvian','Peruvian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Peruvian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Philippine','Philippine' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Philippine') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Pitcairn Islander','Pitcairn Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Pitcairn Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Pohnpeian','Pohnpeian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Pohnpeian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Polish','Polish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Polish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Polish (Old)','Polish (Old)' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Polish (Old)') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Portuguese','Portuguese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Portuguese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Puerto Rican','Puerto Rican' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Puerto Rican') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Qatari','Qatari' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Qatari') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Reunionese','Reunionese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Reunionese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Romanian','Romanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Romanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Russian','Russian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Russian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Rwandan','Rwandan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Rwandan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Sahrawian','Sahrawian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Sahrawian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Saint Helenian','Saint Helenian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Saint Helenian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Saint Lucian','Saint Lucian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Saint Lucian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Saint Vincentian','Saint Vincentian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Saint Vincentian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Salvadoran','Salvadoran' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Salvadoran') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Sammarinese','Sammarinese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Sammarinese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Samoan','Samoan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Samoan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Sao Tomean','Sao Tomean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Sao Tomean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Saudi Arabian','Saudi Arabian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Saudi Arabian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Scottish','Scottish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Scottish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Senegalese','Senegalese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Senegalese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Serbian','Serbian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Serbian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Seychellois','Seychellois' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Seychellois') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Sierra Leonean','Sierra Leonean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Sierra Leonean') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Singapore','Singapore' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Singapore') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Slovak','Slovak' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Slovak') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Slovenian','Slovenian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Slovenian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Solomon Islander','Solomon Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Solomon Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Somali','Somali' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Somali') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'South African','South African' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='South African') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Spanish','Spanish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Spanish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Sri Lankan','Sri Lankan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Sri Lankan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Sudanese','Sudanese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Sudanese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Surinamese','Surinamese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Surinamese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Swazi','Swazi' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Swazi') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Swedish','Swedish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Swedish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Swiss','Swiss' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Swiss') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Syrian','Syrian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Syrian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Taiwanese','Taiwanese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Taiwanese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Tajikistani','Tajikistani' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Tajikistani') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Tanzanian','Tanzanian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Tanzanian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Thai','Thai' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Thai') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Timorese','Timorese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Timorese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Tobagonian','Tobagonian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Tobagonian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Togolese','Togolese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Togolese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Tokelauan','Tokelauan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Tokelauan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Tongan','Tongan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Tongan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Trinidadian','Trinidadian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Trinidadian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Trukese','Trukese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Trukese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Tunisian','Tunisian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Tunisian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Turkish','Turkish' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Turkish') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Turkmen','Turkmen' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Turkmen') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Tuvaluan','Tuvaluan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Tuvaluan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Ugandan','Ugandan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Ugandan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Ukrainian','Ukrainian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Ukrainian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Uruguayan','Uruguayan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Uruguayan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Uzbekistani','Uzbekistani' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Uzbekistani') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Venezuelan','Venezuelan' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Venezuelan') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Vietnamese','Vietnamese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Vietnamese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Virgin Islander','Virgin Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Virgin Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Virgin Islander','Virgin Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Virgin Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Wallis and Futuna Islander','Wallis and Futuna Islander' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Wallis and Futuna Islander') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Welsh','Welsh' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Welsh') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Yapese','Yapese' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Yapese') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Yemeni','Yemeni' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Yemeni') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Yugoslavian','Yugoslavian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Yugoslavian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Zambian','Zambian' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Zambian') LIMIT 1;
INSERT INTO Nationality(countryNumber,nationality) SELECT 'Zimbabwean','Zimbabwean' FROM DUAL WHERE NOT EXISTS (SELECT * FROM Nationality WHERE nationality='Zimbabwean') LIMIT 1;

update Nationality set status = 'INACTIVE';

update Nationality set status = 'CURRENT' where nationality='Afghan';
update Nationality set status = 'CURRENT' where nationality='Albanian';
update Nationality set status = 'CURRENT' where nationality='Algerian';
update Nationality set status = 'CURRENT' where nationality='American';
update Nationality set status = 'CURRENT' where nationality='American Samoan';
update Nationality set status = 'CURRENT' where nationality='Andorran';
update Nationality set status = 'CURRENT' where nationality='Angolan';
update Nationality set status = 'CURRENT' where nationality='Anguillan';
update Nationality set status = 'CURRENT' where nationality='Antiguan';
update Nationality set status = 'CURRENT' where nationality='Argentine';
update Nationality set status = 'CURRENT' where nationality='Armenian';
update Nationality set status = 'CURRENT' where nationality='Aruban';
update Nationality set status = 'CURRENT' where nationality='Australian';
update Nationality set status = 'CURRENT' where nationality='Austrian';
update Nationality set status = 'CURRENT' where nationality='Azerbaijani';
update Nationality set status = 'CURRENT' where nationality='Bahamian';
update Nationality set status = 'CURRENT' where nationality='Bahraini';
update Nationality set status = 'CURRENT' where nationality='Bangladeshi';
update Nationality set status = 'CURRENT' where nationality='Barbadian';
update Nationality set status = 'CURRENT' where nationality='Barbudan';
update Nationality set status = 'CURRENT' where nationality='Basotho';
update Nationality set status = 'CURRENT' where nationality='Belarusian';
update Nationality set status = 'CURRENT' where nationality='Belgian';
update Nationality set status = 'CURRENT' where nationality='Belizean';
update Nationality set status = 'CURRENT' where nationality='Beninese';
update Nationality set status = 'CURRENT' where nationality='Bermudian';
update Nationality set status = 'CURRENT' where nationality='Bhutanese';
update Nationality set status = 'CURRENT' where nationality='Bolivian';
update Nationality set status = 'CURRENT' where nationality='Bosnian';
update Nationality set status = 'CURRENT' where nationality='Brazilian';
update Nationality set status = 'CURRENT' where nationality='British';
update Nationality set status = 'CURRENT' where nationality='British Virgin Islander';
update Nationality set status = 'CURRENT' where nationality='Bruneian';
update Nationality set status = 'CURRENT' where nationality='Bulgarian';
update Nationality set status = 'CURRENT' where nationality='Burkinabe';
update Nationality set status = 'CURRENT' where nationality='Burmese';
update Nationality set status = 'CURRENT' where nationality='Burundi';
update Nationality set status = 'CURRENT' where nationality='Cambodian';
update Nationality set status = 'CURRENT' where nationality='Cameroonian';
update Nationality set status = 'CURRENT' where nationality='Canadian';
update Nationality set status = 'CURRENT' where nationality='Cape Verdean';
update Nationality set status = 'CURRENT' where nationality='Caymanian';
update Nationality set status = 'CURRENT' where nationality='Central African';
update Nationality set status = 'CURRENT' where nationality='Chadian';
update Nationality set status = 'CURRENT' where nationality='Channel Islander';
update Nationality set status = 'CURRENT' where nationality='Chilean';
update Nationality set status = 'CURRENT' where nationality='Chinese';
update Nationality set status = 'CURRENT' where nationality='Christmas Islander';
update Nationality set status = 'CURRENT' where nationality='Chuukese';
update Nationality set status = 'CURRENT' where nationality='Cocos Islander';
update Nationality set status = 'CURRENT' where nationality='Colombian';
update Nationality set status = 'CURRENT' where nationality='Comoran';
update Nationality set status = 'CURRENT' where nationality='Congolese';
update Nationality set status = 'CURRENT' where nationality='Cook Islander';
update Nationality set status = 'CURRENT' where nationality='Costa Rican';
update Nationality set status = 'CURRENT' where nationality='Croatian';
update Nationality set status = 'CURRENT' where nationality='Cuban';
update Nationality set status = 'CURRENT' where nationality='Cypriot';
update Nationality set status = 'CURRENT' where nationality='Czech';
update Nationality set status = 'CURRENT' where nationality='Danish';
update Nationality set status = 'CURRENT' where nationality='Djiboutian';
update Nationality set status = 'CURRENT' where nationality='Dominican';
update Nationality set status = 'CURRENT' where nationality='Dutch';
update Nationality set status = 'CURRENT' where nationality='Dutch Antillean';
update Nationality set status = 'CURRENT' where nationality='Ecuadorian';
update Nationality set status = 'CURRENT' where nationality='Egyptian';
update Nationality set status = 'CURRENT' where nationality='Emirati';
update Nationality set status = 'CURRENT' where nationality='English';
update Nationality set status = 'CURRENT' where nationality='Equatorial Guinean';
update Nationality set status = 'CURRENT' where nationality='Eritrean';
update Nationality set status = 'CURRENT' where nationality='Estonian';
update Nationality set status = 'CURRENT' where nationality='Ethiopian';
update Nationality set status = 'CURRENT' where nationality='Falkland Islander';
update Nationality set status = 'CURRENT' where nationality='Faroese';
update Nationality set status = 'CURRENT' where nationality='Fijian';
update Nationality set status = 'CURRENT' where nationality='Finnish';
update Nationality set status = 'CURRENT' where nationality='French';
update Nationality set status = 'CURRENT' where nationality='French Guianese';
update Nationality set status = 'CURRENT' where nationality='French Polynesian';
update Nationality set status = 'CURRENT' where nationality='Gabonese';
update Nationality set status = 'CURRENT' where nationality='Gambian';
update Nationality set status = 'CURRENT' where nationality='Georgian';
update Nationality set status = 'CURRENT' where nationality='German';
update Nationality set status = 'CURRENT' where nationality='Ghanaian';
update Nationality set status = 'CURRENT' where nationality='Gibraltar';
update Nationality set status = 'CURRENT' where nationality='Greek';
update Nationality set status = 'CURRENT' where nationality='Greenlandic';
update Nationality set status = 'CURRENT' where nationality='Grenadian';
update Nationality set status = 'CURRENT' where nationality='Guadeloupe';
update Nationality set status = 'CURRENT' where nationality='Guamanian';
update Nationality set status = 'CURRENT' where nationality='Guatemalan';
update Nationality set status = 'CURRENT' where nationality='Guinean';
update Nationality set status = 'CURRENT' where nationality='Guyanese';
update Nationality set status = 'CURRENT' where nationality='Haitian';
update Nationality set status = 'CURRENT' where nationality='Honduran';
update Nationality set status = 'CURRENT' where nationality='Hong Kong (British/Chinese)';
update Nationality set status = 'CURRENT' where nationality='Hungarian';
update Nationality set status = 'CURRENT' where nationality='Icelandic';
update Nationality set status = 'CURRENT' where nationality='I-Kiribati';
update Nationality set status = 'CURRENT' where nationality='Indian';
update Nationality set status = 'CURRENT' where nationality='Indonesian';
update Nationality set status = 'CURRENT' where nationality='Iranian';
update Nationality set status = 'CURRENT' where nationality='Iraqi';
update Nationality set status = 'CURRENT' where nationality='Irish';
update Nationality set status = 'CURRENT' where nationality='Israeli';
update Nationality set status = 'CURRENT' where nationality='Italian';
update Nationality set status = 'CURRENT' where nationality='Ivorian';
update Nationality set status = 'CURRENT' where nationality='Jamaican';
update Nationality set status = 'CURRENT' where nationality='Japanese';
update Nationality set status = 'CURRENT' where nationality='Jordanian';
update Nationality set status = 'CURRENT' where nationality='Kazakhstani';
update Nationality set status = 'CURRENT' where nationality='Kenyan';
update Nationality set status = 'CURRENT' where nationality='Kittitian';
update Nationality set status = 'CURRENT' where nationality='Korean';
update Nationality set status = 'CURRENT' where nationality='Korean';
update Nationality set status = 'CURRENT' where nationality='Kosrae';
update Nationality set status = 'CURRENT' where nationality='Kuwaiti';
update Nationality set status = 'CURRENT' where nationality='Kyrgyzstani';
update Nationality set status = 'CURRENT' where nationality='Laotian';
update Nationality set status = 'CURRENT' where nationality='Latin American';
update Nationality set status = 'CURRENT' where nationality='Latvian';
update Nationality set status = 'CURRENT' where nationality='Lebanese';
update Nationality set status = 'CURRENT' where nationality='Liberian';
update Nationality set status = 'CURRENT' where nationality='Libyan';
update Nationality set status = 'CURRENT' where nationality='Liechtenstein';
update Nationality set status = 'CURRENT' where nationality='Lithuanian';
update Nationality set status = 'CURRENT' where nationality='Luxembourg';
update Nationality set status = 'CURRENT' where nationality='Macedonian';
update Nationality set status = 'CURRENT' where nationality='Mahoran';
update Nationality set status = 'CURRENT' where nationality='Malagasy';
update Nationality set status = 'CURRENT' where nationality='Malawian';
update Nationality set status = 'CURRENT' where nationality='Malaysian';
update Nationality set status = 'CURRENT' where nationality='Maldivian';
update Nationality set status = 'CURRENT' where nationality='Malian';
update Nationality set status = 'CURRENT' where nationality='Maltese';
update Nationality set status = 'CURRENT' where nationality='Manx';
update Nationality set status = 'CURRENT' where nationality='Marshallese';
update Nationality set status = 'CURRENT' where nationality='Martiniquais';
update Nationality set status = 'CURRENT' where nationality='Mauritanian';
update Nationality set status = 'CURRENT' where nationality='Mauritian';
update Nationality set status = 'CURRENT' where nationality='Mexican';
update Nationality set status = 'CURRENT' where nationality='Micronesian';
update Nationality set status = 'CURRENT' where nationality='Moldovan';
update Nationality set status = 'CURRENT' where nationality='Monegasque';
update Nationality set status = 'CURRENT' where nationality='Mongolian';
update Nationality set status = 'CURRENT' where nationality='Montenegrin';
update Nationality set status = 'CURRENT' where nationality='Montserratian';
update Nationality set status = 'CURRENT' where nationality='Moroccan';
update Nationality set status = 'CURRENT' where nationality='Motswana';
update Nationality set status = 'CURRENT' where nationality='Mozambican';
update Nationality set status = 'CURRENT' where nationality='Namibian';
update Nationality set status = 'CURRENT' where nationality='Nauruan';
update Nationality set status = 'CURRENT' where nationality='Nepalese';
update Nationality set status = 'CURRENT' where nationality='New Caledonian';
update Nationality set status = 'CURRENT' where nationality='New Zealand';
update Nationality set status = 'CURRENT' where nationality='Nicaraguan';
update Nationality set status = 'CURRENT' where nationality='Nigerian';
update Nationality set status = 'CURRENT' where nationality='Nigerien';
update Nationality set status = 'CURRENT' where nationality='Niuean';
update Nationality set status = 'CURRENT' where nationality='Ni-Vanuatu';
update Nationality set status = 'CURRENT' where nationality='Norfolk Islander';
update Nationality set status = 'CURRENT' where nationality='North Korean ';
update Nationality set status = 'CURRENT' where nationality='Northern Irish';
update Nationality set status = 'CURRENT' where nationality='Norwegian';
update Nationality set status = 'CURRENT' where nationality='Norwegian (Old)';
update Nationality set status = 'CURRENT' where nationality='Omani';
update Nationality set status = 'CURRENT' where nationality='Pakistani';
update Nationality set status = 'CURRENT' where nationality='Palauan';
update Nationality set status = 'CURRENT' where nationality='Palestinian';
update Nationality set status = 'CURRENT' where nationality='Panamanian';
update Nationality set status = 'CURRENT' where nationality='Papua New Guinean';
update Nationality set status = 'CURRENT' where nationality='Paraguayan';
update Nationality set status = 'CURRENT' where nationality='Peruvian';
update Nationality set status = 'CURRENT' where nationality='Philippine';
update Nationality set status = 'CURRENT' where nationality='Pitcairn Islander';
update Nationality set status = 'CURRENT' where nationality='Pohnpeian';
update Nationality set status = 'CURRENT' where nationality='Polish';
update Nationality set status = 'CURRENT' where nationality='Polish (Old)';
update Nationality set status = 'CURRENT' where nationality='Portuguese';
update Nationality set status = 'CURRENT' where nationality='Puerto Rican';
update Nationality set status = 'CURRENT' where nationality='Qatari';
update Nationality set status = 'CURRENT' where nationality='Reunionese';
update Nationality set status = 'CURRENT' where nationality='Romanian';
update Nationality set status = 'CURRENT' where nationality='Russian';
update Nationality set status = 'CURRENT' where nationality='Rwandan';
update Nationality set status = 'CURRENT' where nationality='Sahrawian';
update Nationality set status = 'CURRENT' where nationality='Saint Helenian';
update Nationality set status = 'CURRENT' where nationality='Saint Lucian';
update Nationality set status = 'CURRENT' where nationality='Saint Vincentian';
update Nationality set status = 'CURRENT' where nationality='Salvadoran';
update Nationality set status = 'CURRENT' where nationality='Sammarinese';
update Nationality set status = 'CURRENT' where nationality='Samoan';
update Nationality set status = 'CURRENT' where nationality='Sao Tomean';
update Nationality set status = 'CURRENT' where nationality='Saudi Arabian';
update Nationality set status = 'CURRENT' where nationality='Scottish';
update Nationality set status = 'CURRENT' where nationality='Senegalese';
update Nationality set status = 'CURRENT' where nationality='Serbian';
update Nationality set status = 'CURRENT' where nationality='Seychellois';
update Nationality set status = 'CURRENT' where nationality='Sierra Leonean';
update Nationality set status = 'CURRENT' where nationality='Singapore';
update Nationality set status = 'CURRENT' where nationality='Slovak';
update Nationality set status = 'CURRENT' where nationality='Slovenian';
update Nationality set status = 'CURRENT' where nationality='Solomon Islander';
update Nationality set status = 'CURRENT' where nationality='Somali';
update Nationality set status = 'CURRENT' where nationality='South African';
update Nationality set status = 'CURRENT' where nationality='Spanish';
update Nationality set status = 'CURRENT' where nationality='Sri Lankan';
update Nationality set status = 'CURRENT' where nationality='Sudanese';
update Nationality set status = 'CURRENT' where nationality='Surinamese';
update Nationality set status = 'CURRENT' where nationality='Swazi';
update Nationality set status = 'CURRENT' where nationality='Swedish';
update Nationality set status = 'CURRENT' where nationality='Swiss';
update Nationality set status = 'CURRENT' where nationality='Syrian';
update Nationality set status = 'CURRENT' where nationality='Taiwanese';
update Nationality set status = 'CURRENT' where nationality='Tajikistani';
update Nationality set status = 'CURRENT' where nationality='Tanzanian';
update Nationality set status = 'CURRENT' where nationality='Thai';
update Nationality set status = 'CURRENT' where nationality='Timorese';
update Nationality set status = 'CURRENT' where nationality='Tobagonian';
update Nationality set status = 'CURRENT' where nationality='Togolese';
update Nationality set status = 'CURRENT' where nationality='Tokelauan';
update Nationality set status = 'CURRENT' where nationality='Tongan';
update Nationality set status = 'CURRENT' where nationality='Trinidadian';
update Nationality set status = 'CURRENT' where nationality='Trukese';
update Nationality set status = 'CURRENT' where nationality='Tunisian';
update Nationality set status = 'CURRENT' where nationality='Turkish';
update Nationality set status = 'CURRENT' where nationality='Turkmen';
update Nationality set status = 'CURRENT' where nationality='Tuvaluan';
update Nationality set status = 'CURRENT' where nationality='Ugandan';
update Nationality set status = 'CURRENT' where nationality='Ukrainian';
update Nationality set status = 'CURRENT' where nationality='Uruguayan';
update Nationality set status = 'CURRENT' where nationality='Uzbekistani';
update Nationality set status = 'CURRENT' where nationality='Venezuelan';
update Nationality set status = 'CURRENT' where nationality='Vietnamese';
update Nationality set status = 'CURRENT' where nationality='Virgin Islander';
update Nationality set status = 'CURRENT' where nationality='Virgin Islander';
update Nationality set status = 'CURRENT' where nationality='Wallis and Futuna Islander';
update Nationality set status = 'CURRENT' where nationality='Welsh';
update Nationality set status = 'CURRENT' where nationality='Yapese';
update Nationality set status = 'CURRENT' where nationality='Yemeni';
update Nationality set status = 'CURRENT' where nationality='Yugoslavian';
update Nationality set status = 'CURRENT' where nationality='Zambian';
update Nationality set status = 'CURRENT' where nationality='Zimbabwean';
