insert into country(countrynumber,nationality) select 'Afghanistan','Afghanistan' from dual where not exists (select * from Country where countrynumber='Afghanistan') limit 1;
insert into country(countrynumber,nationality) select 'Aland Islands','Aland Islands' from dual where not exists (select * from Country where countrynumber='Aland Islands') limit 1;
insert into country(countrynumber,nationality) select 'Albania','Albania' from dual where not exists (select * from Country where countrynumber='Albania') limit 1;
insert into country(countrynumber,nationality) select 'Algeria','Algeria' from dual where not exists (select * from Country where countrynumber='Algeria') limit 1;
insert into country(countrynumber,nationality) select 'American Samoa','American Samoa' from dual where not exists (select * from Country where countrynumber='American Samoa') limit 1;
insert into country(countrynumber,nationality) select 'Andorra','Andorra' from dual where not exists (select * from Country where countrynumber='Andorra') limit 1;
insert into country(countrynumber,nationality) select 'Angola','Angola' from dual where not exists (select * from Country where countrynumber='Angola') limit 1;
insert into country(countrynumber,nationality) select 'Anguilla','Anguilla' from dual where not exists (select * from Country where countrynumber='Anguilla') limit 1;
insert into country(countrynumber,nationality) select 'Antarctica','Antarctica' from dual where not exists (select * from Country where countrynumber='Antarctica') limit 1;
insert into country(countrynumber,nationality) select 'Antigua and Barbuda','Antigua and Barbuda' from dual where not exists (select * from Country where countrynumber='Antigua and Barbuda') limit 1;
insert into country(countrynumber,nationality) select 'Argentina','Argentina' from dual where not exists (select * from Country where countrynumber='Argentina') limit 1;
insert into country(countrynumber,nationality) select 'Armenia','Armenia' from dual where not exists (select * from Country where countrynumber='Armenia') limit 1;
insert into country(countrynumber,nationality) select 'Aruba','Aruba' from dual where not exists (select * from Country where countrynumber='Aruba') limit 1;
insert into country(countrynumber,nationality) select 'Australia','Australia' from dual where not exists (select * from Country where countrynumber='Australia') limit 1;
insert into country(countrynumber,nationality) select 'Austria','Austria' from dual where not exists (select * from Country where countrynumber='Austria') limit 1;
insert into country(countrynumber,nationality) select 'Azerbaijan','Azerbaijan' from dual where not exists (select * from Country where countrynumber='Azerbaijan') limit 1;
insert into country(countrynumber,nationality) select 'Bahamas','Bahamas' from dual where not exists (select * from Country where countrynumber='Bahamas') limit 1;
insert into country(countrynumber,nationality) select 'Bahrain','Bahrain' from dual where not exists (select * from Country where countrynumber='Bahrain') limit 1;
insert into country(countrynumber,nationality) select 'Bangladesh','Bangladesh' from dual where not exists (select * from Country where countrynumber='Bangladesh') limit 1;
insert into country(countrynumber,nationality) select 'Barbados','Barbados' from dual where not exists (select * from Country where countrynumber='Barbados') limit 1;
insert into country(countrynumber,nationality) select 'Belarus','Belarus' from dual where not exists (select * from Country where countrynumber='Belarus') limit 1;
insert into country(countrynumber,nationality) select 'Belgium','Belgium' from dual where not exists (select * from Country where countrynumber='Belgium') limit 1;
insert into country(countrynumber,nationality) select 'Belize','Belize' from dual where not exists (select * from Country where countrynumber='Belize') limit 1;
insert into country(countrynumber,nationality) select 'Benin','Benin' from dual where not exists (select * from Country where countrynumber='Benin') limit 1;
insert into country(countrynumber,nationality) select 'Bermuda','Bermuda' from dual where not exists (select * from Country where countrynumber='Bermuda') limit 1;
insert into country(countrynumber,nationality) select 'Bhutan','Bhutan' from dual where not exists (select * from Country where countrynumber='Bhutan') limit 1;
insert into country(countrynumber,nationality) select 'Bolivia, Plurinational State Of','Bolivia, Plurinational State Of' from dual where not exists (select * from Country where countrynumber='Bolivia, Plurinational State Of') limit 1;
insert into country(countrynumber,nationality) select 'Bonaire, Sint Eustatius And Saba','Bonaire, Sint Eustatius And Saba' from dual where not exists (select * from Country where countrynumber='Bonaire, Sint Eustatius And Saba') limit 1;
insert into country(countrynumber,nationality) select 'Bosnia And Herzegovina','Bosnia And Herzegovina' from dual where not exists (select * from Country where countrynumber='Bosnia And Herzegovina') limit 1;
insert into country(countrynumber,nationality) select 'Botswana','Botswana' from dual where not exists (select * from Country where countrynumber='Botswana') limit 1;
insert into country(countrynumber,nationality) select 'Bouvet Island','Bouvet Island' from dual where not exists (select * from Country where countrynumber='Bouvet Island') limit 1;
insert into country(countrynumber,nationality) select 'Brazil','Brazil' from dual where not exists (select * from Country where countrynumber='Brazil') limit 1;
insert into country(countrynumber,nationality) select 'British Indian Ocean Territory','British Indian Ocean Territory' from dual where not exists (select * from Country where countrynumber='British Indian Ocean Territory') limit 1;
insert into country(countrynumber,nationality) select 'Brunei Darussalam','Brunei Darussalam' from dual where not exists (select * from Country where countrynumber='Brunei Darussalam') limit 1;
insert into country(countrynumber,nationality) select 'Bulgaria','Bulgaria' from dual where not exists (select * from Country where countrynumber='Bulgaria') limit 1;
insert into country(countrynumber,nationality) select 'Burkina Faso','Burkina Faso' from dual where not exists (select * from Country where countrynumber='Burkina Faso') limit 1;
insert into country(countrynumber,nationality) select 'Burundi','Burundi' from dual where not exists (select * from Country where countrynumber='Burundi') limit 1;
insert into country(countrynumber,nationality) select 'Cambodia','Cambodia' from dual where not exists (select * from Country where countrynumber='Cambodia') limit 1;
insert into country(countrynumber,nationality) select 'Cameroon','Cameroon' from dual where not exists (select * from Country where countrynumber='Cameroon') limit 1;
insert into country(countrynumber,nationality) select 'Canada','Canada' from dual where not exists (select * from Country where countrynumber='Canada') limit 1;
insert into country(countrynumber,nationality) select 'Cape Verde','Cape Verde' from dual where not exists (select * from Country where countrynumber='Cape Verde') limit 1;
insert into country(countrynumber,nationality) select 'Cayman Islands','Cayman Islands' from dual where not exists (select * from Country where countrynumber='Cayman Islands') limit 1;
insert into country(countrynumber,nationality) select 'Central African Republic','Central African Republic' from dual where not exists (select * from Country where countrynumber='Central African Republic') limit 1;
insert into country(countrynumber,nationality) select 'Chad','Chad' from dual where not exists (select * from Country where countrynumber='Chad') limit 1;
insert into country(countrynumber,nationality) select 'Chile','Chile' from dual where not exists (select * from Country where countrynumber='Chile') limit 1;
insert into country(countrynumber,nationality) select 'China','China' from dual where not exists (select * from Country where countrynumber='China') limit 1;
insert into country(countrynumber,nationality) select 'Christmas Island','Christmas Island' from dual where not exists (select * from Country where countrynumber='Christmas Island') limit 1;
insert into country(countrynumber,nationality) select 'Cocos (Keeling) Islands','Cocos (Keeling) Islands' from dual where not exists (select * from Country where countrynumber='Cocos (Keeling) Islands') limit 1;
insert into country(countrynumber,nationality) select 'Colombia','Colombia' from dual where not exists (select * from Country where countrynumber='Colombia') limit 1;
insert into country(countrynumber,nationality) select 'Comoros','Comoros' from dual where not exists (select * from Country where countrynumber='Comoros') limit 1;
insert into country(countrynumber,nationality) select 'Congo','Congo' from dual where not exists (select * from Country where countrynumber='Congo') limit 1;
insert into country(countrynumber,nationality) select 'Congo, The Democratic Republic of The','Congo, The Democratic Republic of The' from dual where not exists (select * from Country where countrynumber='Congo, The Democratic Republic of The') limit 1;
insert into country(countrynumber,nationality) select 'Cook Islands','Cook Islands' from dual where not exists (select * from Country where countrynumber='Cook Islands') limit 1;
insert into country(countrynumber,nationality) select 'Costa Rica','Costa Rica' from dual where not exists (select * from Country where countrynumber='Costa Rica') limit 1;
insert into country(countrynumber,nationality) select 'Cote D''Ivoire','Cote D''Ivoire' from dual where not exists (select * from Country where countrynumber='Cote D''Ivoire') limit 1;
insert into country(countrynumber,nationality) select 'Croatia','Croatia' from dual where not exists (select * from Country where countrynumber='Croatia') limit 1;
insert into country(countrynumber,nationality) select 'Cuba','Cuba' from dual where not exists (select * from Country where countrynumber='Cuba') limit 1;
insert into country(countrynumber,nationality) select 'Curacao','Curacao' from dual where not exists (select * from Country where countrynumber='Curacao') limit 1;
insert into country(countrynumber,nationality) select 'Cyprus','Cyprus' from dual where not exists (select * from Country where countrynumber='Cyprus') limit 1;
insert into country(countrynumber,nationality) select 'Czech Republic','Czech Republic' from dual where not exists (select * from Country where countrynumber='Czech Republic') limit 1;
insert into country(countrynumber,nationality) select 'Denmark','Denmark' from dual where not exists (select * from Country where countrynumber='Denmark') limit 1;
insert into country(countrynumber,nationality) select 'Djibouti','Djibouti' from dual where not exists (select * from Country where countrynumber='Djibouti') limit 1;
insert into country(countrynumber,nationality) select 'Dominica','Dominica' from dual where not exists (select * from Country where countrynumber='Dominica') limit 1;
insert into country(countrynumber,nationality) select 'Dominican Republic','Dominican Republic' from dual where not exists (select * from Country where countrynumber='Dominican Republic') limit 1;
insert into country(countrynumber,nationality) select 'Ecuador','Ecuador' from dual where not exists (select * from Country where countrynumber='Ecuador') limit 1;
insert into country(countrynumber,nationality) select 'Egypt','Egypt' from dual where not exists (select * from Country where countrynumber='Egypt') limit 1;
insert into country(countrynumber,nationality) select 'El Salvador','El Salvador' from dual where not exists (select * from Country where countrynumber='El Salvador') limit 1;
insert into country(countrynumber,nationality) select 'Equatorial Guinea','Equatorial Guinea' from dual where not exists (select * from Country where countrynumber='Equatorial Guinea') limit 1;
insert into country(countrynumber,nationality) select 'Eritrea','Eritrea' from dual where not exists (select * from Country where countrynumber='Eritrea') limit 1;
insert into country(countrynumber,nationality) select 'Estonia','Estonia' from dual where not exists (select * from Country where countrynumber='Estonia') limit 1;
insert into country(countrynumber,nationality) select 'Ethiopia','Ethiopia' from dual where not exists (select * from Country where countrynumber='Ethiopia') limit 1;
insert into country(countrynumber,nationality) select 'Falkland Islands (Malvinas)','Falkland Islands (Malvinas)' from dual where not exists (select * from Country where countrynumber='Falkland Islands (Malvinas)') limit 1;
insert into country(countrynumber,nationality) select 'Faroe Islands','Faroe Islands' from dual where not exists (select * from Country where countrynumber='Faroe Islands') limit 1;
insert into country(countrynumber,nationality) select 'Fiji','Fiji' from dual where not exists (select * from Country where countrynumber='Fiji') limit 1;
insert into country(countrynumber,nationality) select 'Finland','Finland' from dual where not exists (select * from Country where countrynumber='Finland') limit 1;
insert into country(countrynumber,nationality) select 'France','France' from dual where not exists (select * from Country where countrynumber='France') limit 1;
insert into country(countrynumber,nationality) select 'French Guiana','French Guiana' from dual where not exists (select * from Country where countrynumber='French Guiana') limit 1;
insert into country(countrynumber,nationality) select 'French Polynesia','French Polynesia' from dual where not exists (select * from Country where countrynumber='French Polynesia') limit 1;
insert into country(countrynumber,nationality) select 'French Southern Territories','French Southern Territories' from dual where not exists (select * from Country where countrynumber='French Southern Territories') limit 1;
insert into country(countrynumber,nationality) select 'Gabon','Gabon' from dual where not exists (select * from Country where countrynumber='Gabon') limit 1;
insert into country(countrynumber,nationality) select 'Gambia','Gambia' from dual where not exists (select * from Country where countrynumber='Gambia') limit 1;
insert into country(countrynumber,nationality) select 'Georgia','Georgia' from dual where not exists (select * from Country where countrynumber='Georgia') limit 1;
insert into country(countrynumber,nationality) select 'Germany','Germany' from dual where not exists (select * from Country where countrynumber='Germany') limit 1;
insert into country(countrynumber,nationality) select 'Ghana','Ghana' from dual where not exists (select * from Country where countrynumber='Ghana') limit 1;
insert into country(countrynumber,nationality) select 'Gibraltar','Gibraltar' from dual where not exists (select * from Country where countrynumber='Gibraltar') limit 1;
insert into country(countrynumber,nationality) select 'Greece','Greece' from dual where not exists (select * from Country where countrynumber='Greece') limit 1;
insert into country(countrynumber,nationality) select 'Greenland','Greenland' from dual where not exists (select * from Country where countrynumber='Greenland') limit 1;
insert into country(countrynumber,nationality) select 'Grenada','Grenada' from dual where not exists (select * from Country where countrynumber='Grenada') limit 1;
insert into country(countrynumber,nationality) select 'Guadeloupe','Guadeloupe' from dual where not exists (select * from Country where countrynumber='Guadeloupe') limit 1;
insert into country(countrynumber,nationality) select 'Guam','Guam' from dual where not exists (select * from Country where countrynumber='Guam') limit 1;
insert into country(countrynumber,nationality) select 'Guatemala','Guatemala' from dual where not exists (select * from Country where countrynumber='Guatemala') limit 1;
insert into country(countrynumber,nationality) select 'Guernsey','Guernsey' from dual where not exists (select * from Country where countrynumber='Guernsey') limit 1;
insert into country(countrynumber,nationality) select 'Guinea','Guinea' from dual where not exists (select * from Country where countrynumber='Guinea') limit 1;
insert into country(countrynumber,nationality) select 'Guinea-Bissau','Guinea-Bissau' from dual where not exists (select * from Country where countrynumber='Guinea-Bissau') limit 1;
insert into country(countrynumber,nationality) select 'Guyana','Guyana' from dual where not exists (select * from Country where countrynumber='Guyana') limit 1;
insert into country(countrynumber,nationality) select 'Haiti','Haiti' from dual where not exists (select * from Country where countrynumber='Haiti') limit 1;
insert into country(countrynumber,nationality) select 'Heard Island And Mcdonald Islands','Heard Island And Mcdonald Islands' from dual where not exists (select * from Country where countrynumber='Heard Island And Mcdonald Islands') limit 1;
insert into country(countrynumber,nationality) select 'Holy See (Vatican City State)','Holy See (Vatican City State)' from dual where not exists (select * from Country where countrynumber='Holy See (Vatican City State)') limit 1;
insert into country(countrynumber,nationality) select 'Honduras','Honduras' from dual where not exists (select * from Country where countrynumber='Honduras') limit 1;
insert into country(countrynumber,nationality) select 'Hong Kong','Hong Kong' from dual where not exists (select * from Country where countrynumber='Hong Kong') limit 1;
insert into country(countrynumber,nationality) select 'Hungary','Hungary' from dual where not exists (select * from Country where countrynumber='Hungary') limit 1;
insert into country(countrynumber,nationality) select 'Iceland','Iceland' from dual where not exists (select * from Country where countrynumber='Iceland') limit 1;
insert into country(countrynumber,nationality) select 'India','India' from dual where not exists (select * from Country where countrynumber='India') limit 1;
insert into country(countrynumber,nationality) select 'Indonesia','Indonesia' from dual where not exists (select * from Country where countrynumber='Indonesia') limit 1;
insert into country(countrynumber,nationality) select 'Iran, Islamic Republic Of','Iran, Islamic Republic Of' from dual where not exists (select * from Country where countrynumber='Iran, Islamic Republic Of') limit 1;
insert into country(countrynumber,nationality) select 'Iraq','Iraq' from dual where not exists (select * from Country where countrynumber='Iraq') limit 1;
insert into country(countrynumber,nationality) select 'Ireland','Ireland' from dual where not exists (select * from Country where countrynumber='Ireland') limit 1;
insert into country(countrynumber,nationality) select 'Isle of Man','Isle of Man' from dual where not exists (select * from Country where countrynumber='Isle of Man') limit 1;
insert into country(countrynumber,nationality) select 'Israel','Israel' from dual where not exists (select * from Country where countrynumber='Israel') limit 1;
insert into country(countrynumber,nationality) select 'Italy','Italy' from dual where not exists (select * from Country where countrynumber='Italy') limit 1;
insert into country(countrynumber,nationality) select 'Jamaica','Jamaica' from dual where not exists (select * from Country where countrynumber='Jamaica') limit 1;
insert into country(countrynumber,nationality) select 'Japan','Japan' from dual where not exists (select * from Country where countrynumber='Japan') limit 1;
insert into country(countrynumber,nationality) select 'Jersey','Jersey' from dual where not exists (select * from Country where countrynumber='Jersey') limit 1;
insert into country(countrynumber,nationality) select 'Jordan','Jordan' from dual where not exists (select * from Country where countrynumber='Jordan') limit 1;
insert into country(countrynumber,nationality) select 'Kazakhstan','Kazakhstan' from dual where not exists (select * from Country where countrynumber='Kazakhstan') limit 1;
insert into country(countrynumber,nationality) select 'Kenya','Kenya' from dual where not exists (select * from Country where countrynumber='Kenya') limit 1;
insert into country(countrynumber,nationality) select 'Kiribati','Kiribati' from dual where not exists (select * from Country where countrynumber='Kiribati') limit 1;
insert into country(countrynumber,nationality) select 'Korea, Democratic People''s Republic Of','Korea, Democratic People''s Republic Of' from dual where not exists (select * from Country where countrynumber='Korea, Democratic People''s Republic Of') limit 1;
insert into country(countrynumber,nationality) select 'Korea, Republic Of','Korea, Republic Of' from dual where not exists (select * from Country where countrynumber='Korea, Republic Of') limit 1;
insert into country(countrynumber,nationality) select 'Kuwait','Kuwait' from dual where not exists (select * from Country where countrynumber='Kuwait') limit 1;
insert into country(countrynumber,nationality) select 'Kyrgyzstan','Kyrgyzstan' from dual where not exists (select * from Country where countrynumber='Kyrgyzstan') limit 1;
insert into country(countrynumber,nationality) select 'Lao People''s Democratic Republic','Lao People''s Democratic Republic' from dual where not exists (select * from Country where countrynumber='Lao People''s Democratic Republic') limit 1;
insert into country(countrynumber,nationality) select 'Latvia','Latvia' from dual where not exists (select * from Country where countrynumber='Latvia') limit 1;
insert into country(countrynumber,nationality) select 'Lebanon','Lebanon' from dual where not exists (select * from Country where countrynumber='Lebanon') limit 1;
insert into country(countrynumber,nationality) select 'Lesotho','Lesotho' from dual where not exists (select * from Country where countrynumber='Lesotho') limit 1;
insert into country(countrynumber,nationality) select 'Liberia','Liberia' from dual where not exists (select * from Country where countrynumber='Liberia') limit 1;
insert into country(countrynumber,nationality) select 'Libya','Libya' from dual where not exists (select * from Country where countrynumber='Libya') limit 1;
insert into country(countrynumber,nationality) select 'Liechtenstein','Liechtenstein' from dual where not exists (select * from Country where countrynumber='Liechtenstein') limit 1;
insert into country(countrynumber,nationality) select 'Lithuania','Lithuania' from dual where not exists (select * from Country where countrynumber='Lithuania') limit 1;
insert into country(countrynumber,nationality) select 'Luxembourg','Luxembourg' from dual where not exists (select * from Country where countrynumber='Luxembourg') limit 1;
insert into country(countrynumber,nationality) select 'Macao','Macao' from dual where not exists (select * from Country where countrynumber='Macao') limit 1;
insert into country(countrynumber,nationality) select 'Macedonia, The Former Yugoslav Republic of','Macedonia, The Former Yugoslav Republic of' from dual where not exists (select * from Country where countrynumber='Macedonia, The Former Yugoslav Republic of') limit 1;
insert into country(countrynumber,nationality) select 'Madagascar','Madagascar' from dual where not exists (select * from Country where countrynumber='Madagascar') limit 1;
insert into country(countrynumber,nationality) select 'Malawi','Malawi' from dual where not exists (select * from Country where countrynumber='Malawi') limit 1;
insert into country(countrynumber,nationality) select 'Malaysia','Malaysia' from dual where not exists (select * from Country where countrynumber='Malaysia') limit 1;
insert into country(countrynumber,nationality) select 'Maldives','Maldives' from dual where not exists (select * from Country where countrynumber='Maldives') limit 1;
insert into country(countrynumber,nationality) select 'Mali','Mali' from dual where not exists (select * from Country where countrynumber='Mali') limit 1;
insert into country(countrynumber,nationality) select 'Malta','Malta' from dual where not exists (select * from Country where countrynumber='Malta') limit 1;
insert into country(countrynumber,nationality) select 'Marshall Islands','Marshall Islands' from dual where not exists (select * from Country where countrynumber='Marshall Islands') limit 1;
insert into country(countrynumber,nationality) select 'Martinique','Martinique' from dual where not exists (select * from Country where countrynumber='Martinique') limit 1;
insert into country(countrynumber,nationality) select 'Mauritania','Mauritania' from dual where not exists (select * from Country where countrynumber='Mauritania') limit 1;
insert into country(countrynumber,nationality) select 'Mauritius','Mauritius' from dual where not exists (select * from Country where countrynumber='Mauritius') limit 1;
insert into country(countrynumber,nationality) select 'Mayotte','Mayotte' from dual where not exists (select * from Country where countrynumber='Mayotte') limit 1;
insert into country(countrynumber,nationality) select 'Mexico','Mexico' from dual where not exists (select * from Country where countrynumber='Mexico') limit 1;
insert into country(countrynumber,nationality) select 'Micronesia, Federated States Of','Micronesia, Federated States Of' from dual where not exists (select * from Country where countrynumber='Micronesia, Federated States Of') limit 1;
insert into country(countrynumber,nationality) select 'Moldova, Republic Of','Moldova, Republic Of' from dual where not exists (select * from Country where countrynumber='Moldova, Republic Of') limit 1;
insert into country(countrynumber,nationality) select 'Monaco','Monaco' from dual where not exists (select * from Country where countrynumber='Monaco') limit 1;
insert into country(countrynumber,nationality) select 'Mongolia','Mongolia' from dual where not exists (select * from Country where countrynumber='Mongolia') limit 1;
insert into country(countrynumber,nationality) select 'Montenegro','Montenegro' from dual where not exists (select * from Country where countrynumber='Montenegro') limit 1;
insert into country(countrynumber,nationality) select 'Montserrat','Montserrat' from dual where not exists (select * from Country where countrynumber='Montserrat') limit 1;
insert into country(countrynumber,nationality) select 'Morocco','Morocco' from dual where not exists (select * from Country where countrynumber='Morocco') limit 1;
insert into country(countrynumber,nationality) select 'Mozambique','Mozambique' from dual where not exists (select * from Country where countrynumber='Mozambique') limit 1;
insert into country(countrynumber,nationality) select 'Myanmar','Myanmar' from dual where not exists (select * from Country where countrynumber='Myanmar') limit 1;
insert into country(countrynumber,nationality) select 'Namibia','Namibia' from dual where not exists (select * from Country where countrynumber='Namibia') limit 1;
insert into country(countrynumber,nationality) select 'Nauru','Nauru' from dual where not exists (select * from Country where countrynumber='Nauru') limit 1;
insert into country(countrynumber,nationality) select 'Nepal','Nepal' from dual where not exists (select * from Country where countrynumber='Nepal') limit 1;
insert into country(countrynumber,nationality) select 'Netherlands','Netherlands' from dual where not exists (select * from Country where countrynumber='Netherlands') limit 1;
insert into country(countrynumber,nationality) select 'New Caledonia','New Caledonia' from dual where not exists (select * from Country where countrynumber='New Caledonia') limit 1;
insert into country(countrynumber,nationality) select 'New Zealand','New Zealand' from dual where not exists (select * from Country where countrynumber='New Zealand') limit 1;
insert into country(countrynumber,nationality) select 'Nicaragua','Nicaragua' from dual where not exists (select * from Country where countrynumber='Nicaragua') limit 1;
insert into country(countrynumber,nationality) select 'Niger','Niger' from dual where not exists (select * from Country where countrynumber='Niger') limit 1;
insert into country(countrynumber,nationality) select 'Nigeria','Nigeria' from dual where not exists (select * from Country where countrynumber='Nigeria') limit 1;
insert into country(countrynumber,nationality) select 'Niue','Niue' from dual where not exists (select * from Country where countrynumber='Niue') limit 1;
insert into country(countrynumber,nationality) select 'Norfolk Island','Norfolk Island' from dual where not exists (select * from Country where countrynumber='Norfolk Island') limit 1;
insert into country(countrynumber,nationality) select 'Northern Mariana Islands','Northern Mariana Islands' from dual where not exists (select * from Country where countrynumber='Northern Mariana Islands') limit 1;
insert into country(countrynumber,nationality) select 'Norway','Norway' from dual where not exists (select * from Country where countrynumber='Norway') limit 1;
insert into country(countrynumber,nationality) select 'Oman','Oman' from dual where not exists (select * from Country where countrynumber='Oman') limit 1;
insert into country(countrynumber,nationality) select 'Pakistan','Pakistan' from dual where not exists (select * from Country where countrynumber='Pakistan') limit 1;
insert into country(countrynumber,nationality) select 'Palau','Palau' from dual where not exists (select * from Country where countrynumber='Palau') limit 1;
insert into country(countrynumber,nationality) select 'Palestine, State of','Palestine, State of' from dual where not exists (select * from Country where countrynumber='Palestine, State of') limit 1;
insert into country(countrynumber,nationality) select 'Panama','Panama' from dual where not exists (select * from Country where countrynumber='Panama') limit 1;
insert into country(countrynumber,nationality) select 'Papua New Guinea','Papua New Guinea' from dual where not exists (select * from Country where countrynumber='Papua New Guinea') limit 1;
insert into country(countrynumber,nationality) select 'Paraguay','Paraguay' from dual where not exists (select * from Country where countrynumber='Paraguay') limit 1;
insert into country(countrynumber,nationality) select 'Peru','Peru' from dual where not exists (select * from Country where countrynumber='Peru') limit 1;
insert into country(countrynumber,nationality) select 'Philippines','Philippines' from dual where not exists (select * from Country where countrynumber='Philippines') limit 1;
insert into country(countrynumber,nationality) select 'Pitcairn','Pitcairn' from dual where not exists (select * from Country where countrynumber='Pitcairn') limit 1;
insert into country(countrynumber,nationality) select 'Poland','Poland' from dual where not exists (select * from Country where countrynumber='Poland') limit 1;
insert into country(countrynumber,nationality) select 'Portugal','Portugal' from dual where not exists (select * from Country where countrynumber='Portugal') limit 1;
insert into country(countrynumber,nationality) select 'Puerto Rico','Puerto Rico' from dual where not exists (select * from Country where countrynumber='Puerto Rico') limit 1;
insert into country(countrynumber,nationality) select 'Qatar','Qatar' from dual where not exists (select * from Country where countrynumber='Qatar') limit 1;
insert into country(countrynumber,nationality) select 'Reunion','Reunion' from dual where not exists (select * from Country where countrynumber='Reunion') limit 1;
insert into country(countrynumber,nationality) select 'Romania','Romania' from dual where not exists (select * from Country where countrynumber='Romania') limit 1;
insert into country(countrynumber,nationality) select 'Russian Federation','Russian Federation' from dual where not exists (select * from Country where countrynumber='Russian Federation') limit 1;
insert into country(countrynumber,nationality) select 'Rwanda','Rwanda' from dual where not exists (select * from Country where countrynumber='Rwanda') limit 1;
insert into country(countrynumber,nationality) select 'Saint Barthelemy','Saint Barthelemy' from dual where not exists (select * from Country where countrynumber='Saint Barthelemy') limit 1;
insert into country(countrynumber,nationality) select 'Saint Helena, Ascension And Tristan Da Cunha','Saint Helena, Ascension And Tristan Da Cunha' from dual where not exists (select * from Country where countrynumber='Saint Helena, Ascension And Tristan Da Cunha') limit 1;
insert into country(countrynumber,nationality) select 'Saint Kitts And Nevis','Saint Kitts And Nevis' from dual where not exists (select * from Country where countrynumber='Saint Kitts And Nevis') limit 1;
insert into country(countrynumber,nationality) select 'Saint Lucia','Saint Lucia' from dual where not exists (select * from Country where countrynumber='Saint Lucia') limit 1;
insert into country(countrynumber,nationality) select 'Saint Martin (French Part)','Saint Martin (French Part)' from dual where not exists (select * from Country where countrynumber='Saint Martin (French Part)') limit 1;
insert into country(countrynumber,nationality) select 'Saint Pierre And Miquelon','Saint Pierre And Miquelon' from dual where not exists (select * from Country where countrynumber='Saint Pierre And Miquelon') limit 1;
insert into country(countrynumber,nationality) select 'Saint Vincent And The Grenadines','Saint Vincent And The Grenadines' from dual where not exists (select * from Country where countrynumber='Saint Vincent And The Grenadines') limit 1;
insert into country(countrynumber,nationality) select 'Samoa','Samoa' from dual where not exists (select * from Country where countrynumber='Samoa') limit 1;
insert into country(countrynumber,nationality) select 'San Marino','San Marino' from dual where not exists (select * from Country where countrynumber='San Marino') limit 1;
insert into country(countrynumber,nationality) select 'Sao Tome And Principe','Sao Tome And Principe' from dual where not exists (select * from Country where countrynumber='Sao Tome And Principe') limit 1;
insert into country(countrynumber,nationality) select 'Saudi Arabia','Saudi Arabia' from dual where not exists (select * from Country where countrynumber='Saudi Arabia') limit 1;
insert into country(countrynumber,nationality) select 'Senegal','Senegal' from dual where not exists (select * from Country where countrynumber='Senegal') limit 1;
insert into country(countrynumber,nationality) select 'Serbia','Serbia' from dual where not exists (select * from Country where countrynumber='Serbia') limit 1;
insert into country(countrynumber,nationality) select 'Seychelles','Seychelles' from dual where not exists (select * from Country where countrynumber='Seychelles') limit 1;
insert into country(countrynumber,nationality) select 'Sierra Leone','Sierra Leone' from dual where not exists (select * from Country where countrynumber='Sierra Leone') limit 1;
insert into country(countrynumber,nationality) select 'Singapore','Singapore' from dual where not exists (select * from Country where countrynumber='Singapore') limit 1;
insert into country(countrynumber,nationality) select 'Sint Maarten (Dutch Part)','Sint Maarten (Dutch Part)' from dual where not exists (select * from Country where countrynumber='Sint Maarten (Dutch Part)') limit 1;
insert into country(countrynumber,nationality) select 'Slovakia','Slovakia' from dual where not exists (select * from Country where countrynumber='Slovakia') limit 1;
insert into country(countrynumber,nationality) select 'Slovenia','Slovenia' from dual where not exists (select * from Country where countrynumber='Slovenia') limit 1;
insert into country(countrynumber,nationality) select 'Solomon Islands','Solomon Islands' from dual where not exists (select * from Country where countrynumber='Solomon Islands') limit 1;
insert into country(countrynumber,nationality) select 'Somalia','Somalia' from dual where not exists (select * from Country where countrynumber='Somalia') limit 1;
insert into country(countrynumber,nationality) select 'South Africa','South Africa' from dual where not exists (select * from Country where countrynumber='South Africa') limit 1;
insert into country(countrynumber,nationality) select 'South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands' from dual where not exists (select * from Country where countrynumber='South Georgia and the South Sandwich Islands') limit 1;
insert into country(countrynumber,nationality) select 'South Sudan','South Sudan' from dual where not exists (select * from Country where countrynumber='South Sudan') limit 1;
insert into country(countrynumber,nationality) select 'Spain','Spain' from dual where not exists (select * from Country where countrynumber='Spain') limit 1;
insert into country(countrynumber,nationality) select 'Sri Lanka','Sri Lanka' from dual where not exists (select * from Country where countrynumber='Sri Lanka') limit 1;
insert into country(countrynumber,nationality) select 'Sudan','Sudan' from dual where not exists (select * from Country where countrynumber='Sudan') limit 1;
insert into country(countrynumber,nationality) select 'Suriname','Suriname' from dual where not exists (select * from Country where countrynumber='Suriname') limit 1;
insert into country(countrynumber,nationality) select 'Svalbard And Jan Mayen','Svalbard And Jan Mayen' from dual where not exists (select * from Country where countrynumber='Svalbard And Jan Mayen') limit 1;
insert into country(countrynumber,nationality) select 'Swaziland','Swaziland' from dual where not exists (select * from Country where countrynumber='Swaziland') limit 1;
insert into country(countrynumber,nationality) select 'Sweden','Sweden' from dual where not exists (select * from Country where countrynumber='Sweden') limit 1;
insert into country(countrynumber,nationality) select 'Switzerland','Switzerland' from dual where not exists (select * from Country where countrynumber='Switzerland') limit 1;
insert into country(countrynumber,nationality) select 'Syrian Arab Republic','Syrian Arab Republic' from dual where not exists (select * from Country where countrynumber='Syrian Arab Republic') limit 1;
insert into country(countrynumber,nationality) select 'Taiwan, Province Of China','Taiwan, Province Of China' from dual where not exists (select * from Country where countrynumber='Taiwan, Province Of China') limit 1;
insert into country(countrynumber,nationality) select 'Tajikistan','Tajikistan' from dual where not exists (select * from Country where countrynumber='Tajikistan') limit 1;
insert into country(countrynumber,nationality) select 'Tanzania, United Republic Of','Tanzania, United Republic Of' from dual where not exists (select * from Country where countrynumber='Tanzania, United Republic Of') limit 1;
insert into country(countrynumber,nationality) select 'Thailand','Thailand' from dual where not exists (select * from Country where countrynumber='Thailand') limit 1;
insert into country(countrynumber,nationality) select 'Timor-Leste','Timor-Leste' from dual where not exists (select * from Country where countrynumber='Timor-Leste') limit 1;
insert into country(countrynumber,nationality) select 'Togo','Togo' from dual where not exists (select * from Country where countrynumber='Togo') limit 1;
insert into country(countrynumber,nationality) select 'Tokelau','Tokelau' from dual where not exists (select * from Country where countrynumber='Tokelau') limit 1;
insert into country(countrynumber,nationality) select 'Tonga','Tonga' from dual where not exists (select * from Country where countrynumber='Tonga') limit 1;
insert into country(countrynumber,nationality) select 'Trinidad And Tobago','Trinidad And Tobago' from dual where not exists (select * from Country where countrynumber='Trinidad And Tobago') limit 1;
insert into country(countrynumber,nationality) select 'Tunisia','Tunisia' from dual where not exists (select * from Country where countrynumber='Tunisia') limit 1;
insert into country(countrynumber,nationality) select 'Turkey','Turkey' from dual where not exists (select * from Country where countrynumber='Turkey') limit 1;
insert into country(countrynumber,nationality) select 'Turkmenistan','Turkmenistan' from dual where not exists (select * from Country where countrynumber='Turkmenistan') limit 1;
insert into country(countrynumber,nationality) select 'Turks And Caicos Islands','Turks And Caicos Islands' from dual where not exists (select * from Country where countrynumber='Turks And Caicos Islands') limit 1;
insert into country(countrynumber,nationality) select 'Tuvalu','Tuvalu' from dual where not exists (select * from Country where countrynumber='Tuvalu') limit 1;
insert into country(countrynumber,nationality) select 'Uganda','Uganda' from dual where not exists (select * from Country where countrynumber='Uganda') limit 1;
insert into country(countrynumber,nationality) select 'Ukraine','Ukraine' from dual where not exists (select * from Country where countrynumber='Ukraine') limit 1;
insert into country(countrynumber,nationality) select 'United Arab Emirates','United Arab Emirates' from dual where not exists (select * from Country where countrynumber='United Arab Emirates') limit 1;
insert into country(countrynumber,nationality) select 'United Kingdom','United Kingdom' from dual where not exists (select * from Country where countrynumber='United Kingdom') limit 1;
insert into country(countrynumber,nationality) select 'United States','United States' from dual where not exists (select * from Country where countrynumber='United States') limit 1;
insert into country(countrynumber,nationality) select 'United States Minor Outlying Islands','United States Minor Outlying Islands' from dual where not exists (select * from Country where countrynumber='United States Minor Outlying Islands') limit 1;
insert into country(countrynumber,nationality) select 'Uruguay','Uruguay' from dual where not exists (select * from Country where countrynumber='Uruguay') limit 1;
insert into country(countrynumber,nationality) select 'Uzbekistan','Uzbekistan' from dual where not exists (select * from Country where countrynumber='Uzbekistan') limit 1;
insert into country(countrynumber,nationality) select 'Vanuatu','Vanuatu' from dual where not exists (select * from Country where countrynumber='Vanuatu') limit 1;
insert into country(countrynumber,nationality) select 'Venezuela, Bolivarian Republic Of','Venezuela, Bolivarian Republic Of' from dual where not exists (select * from Country where countrynumber='Venezuela, Bolivarian Republic Of') limit 1;
insert into country(countrynumber,nationality) select 'Vietnam','Vietnam' from dual where not exists (select * from Country where countrynumber='Vietnam') limit 1;
insert into country(countrynumber,nationality) select 'Virgin Islands, British','Virgin Islands, British' from dual where not exists (select * from Country where countrynumber='Virgin Islands, British') limit 1;
insert into country(countrynumber,nationality) select 'Virgin Islands, U.S.','Virgin Islands, U.S.' from dual where not exists (select * from Country where countrynumber='Virgin Islands, U.S.') limit 1;
insert into country(countrynumber,nationality) select 'Wallis And Futuna','Wallis And Futuna' from dual where not exists (select * from Country where countrynumber='Wallis And Futuna') limit 1;
insert into country(countrynumber,nationality) select 'Western Sahara','Western Sahara' from dual where not exists (select * from Country where countrynumber='Western Sahara') limit 1;
insert into country(countrynumber,nationality) select 'Yemen','Yemen' from dual where not exists (select * from Country where countrynumber='Yemen') limit 1;
insert into country(countrynumber,nationality) select 'Zambia','Zambia' from dual where not exists (select * from Country where countrynumber='Zambia') limit 1;
insert into country(countrynumber,nationality) select 'Zimbabwe','Zimbabwe' from dual where not exists (select * from Country where countrynumber='Zimbabwe') limit 1;

update Country set status = 'INACTIVE';

update Country set status = 'CURRENT' where countryNumber='Afghanistan';
update Country set status = 'CURRENT' where countryNumber='Aland Islands';
update Country set status = 'CURRENT' where countryNumber='Albania';
update Country set status = 'CURRENT' where countryNumber='Algeria';
update Country set status = 'CURRENT' where countryNumber='American Samoa';
update Country set status = 'CURRENT' where countryNumber='Andorra';
update Country set status = 'CURRENT' where countryNumber='Angola';
update Country set status = 'CURRENT' where countryNumber='Anguilla';
update Country set status = 'CURRENT' where countryNumber='Antarctica';
update Country set status = 'CURRENT' where countryNumber='Antigua and Barbuda';
update Country set status = 'CURRENT' where countryNumber='Argentina';
update Country set status = 'CURRENT' where countryNumber='Armenia';
update Country set status = 'CURRENT' where countryNumber='Aruba';
update Country set status = 'CURRENT' where countryNumber='Australia';
update Country set status = 'CURRENT' where countryNumber='Austria';
update Country set status = 'CURRENT' where countryNumber='Azerbaijan';
update Country set status = 'CURRENT' where countryNumber='Bahamas';
update Country set status = 'CURRENT' where countryNumber='Bahrain';
update Country set status = 'CURRENT' where countryNumber='Bangladesh';
update Country set status = 'CURRENT' where countryNumber='Barbados';
update Country set status = 'CURRENT' where countryNumber='Belarus';
update Country set status = 'CURRENT' where countryNumber='Belgium';
update Country set status = 'CURRENT' where countryNumber='Belize';
update Country set status = 'CURRENT' where countryNumber='Benin';
update Country set status = 'CURRENT' where countryNumber='Bermuda';
update Country set status = 'CURRENT' where countryNumber='Bhutan';
update Country set status = 'CURRENT' where countryNumber='Bolivia, Plurinational State Of';
update Country set status = 'CURRENT' where countryNumber='Bonaire, Sint Eustatius And Saba';
update Country set status = 'CURRENT' where countryNumber='Bosnia And Herzegovina';
update Country set status = 'CURRENT' where countryNumber='Botswana';
update Country set status = 'CURRENT' where countryNumber='Bouvet Island';
update Country set status = 'CURRENT' where countryNumber='Brazil';
update Country set status = 'CURRENT' where countryNumber='British Indian Ocean Territory';
update Country set status = 'CURRENT' where countryNumber='Brunei Darussalam';
update Country set status = 'CURRENT' where countryNumber='Bulgaria';
update Country set status = 'CURRENT' where countryNumber='Burkina Faso';
update Country set status = 'CURRENT' where countryNumber='Burundi';
update Country set status = 'CURRENT' where countryNumber='Cambodia';
update Country set status = 'CURRENT' where countryNumber='Cameroon';
update Country set status = 'CURRENT' where countryNumber='Canada';
update Country set status = 'CURRENT' where countryNumber='Cape Verde';
update Country set status = 'CURRENT' where countryNumber='Cayman Islands';
update Country set status = 'CURRENT' where countryNumber='Central African Republic';
update Country set status = 'CURRENT' where countryNumber='Chad';
update Country set status = 'CURRENT' where countryNumber='Chile';
update Country set status = 'CURRENT' where countryNumber='China';
update Country set status = 'CURRENT' where countryNumber='Christmas Island';
update Country set status = 'CURRENT' where countryNumber='Cocos (Keeling) Islands';
update Country set status = 'CURRENT' where countryNumber='Colombia';
update Country set status = 'CURRENT' where countryNumber='Comoros';
update Country set status = 'CURRENT' where countryNumber='Congo';
update Country set status = 'CURRENT' where countryNumber='Congo, The Democratic Republic of The';
update Country set status = 'CURRENT' where countryNumber='Cook Islands';
update Country set status = 'CURRENT' where countryNumber='Costa Rica';
update Country set status = 'CURRENT' where countryNumber='Cote D''Ivoire';
update Country set status = 'CURRENT' where countryNumber='Croatia';
update Country set status = 'CURRENT' where countryNumber='Cuba';
update Country set status = 'CURRENT' where countryNumber='Curacao';
update Country set status = 'CURRENT' where countryNumber='Cyprus';
update Country set status = 'CURRENT' where countryNumber='Czech Republic';
update Country set status = 'CURRENT' where countryNumber='Denmark';
update Country set status = 'CURRENT' where countryNumber='Djibouti';
update Country set status = 'CURRENT' where countryNumber='Dominica';
update Country set status = 'CURRENT' where countryNumber='Dominican Republic';
update Country set status = 'CURRENT' where countryNumber='Ecuador';
update Country set status = 'CURRENT' where countryNumber='Egypt';
update Country set status = 'CURRENT' where countryNumber='El Salvador';
update Country set status = 'CURRENT' where countryNumber='Equatorial Guinea';
update Country set status = 'CURRENT' where countryNumber='Eritrea';
update Country set status = 'CURRENT' where countryNumber='Estonia';
update Country set status = 'CURRENT' where countryNumber='Ethiopia';
update Country set status = 'CURRENT' where countryNumber='Falkland Islands (Malvinas)';
update Country set status = 'CURRENT' where countryNumber='Faroe Islands';
update Country set status = 'CURRENT' where countryNumber='Fiji';
update Country set status = 'CURRENT' where countryNumber='Finland';
update Country set status = 'CURRENT' where countryNumber='France';
update Country set status = 'CURRENT' where countryNumber='French Guiana';
update Country set status = 'CURRENT' where countryNumber='French Polynesia';
update Country set status = 'CURRENT' where countryNumber='French Southern Territories';
update Country set status = 'CURRENT' where countryNumber='Gabon';
update Country set status = 'CURRENT' where countryNumber='Gambia';
update Country set status = 'CURRENT' where countryNumber='Georgia';
update Country set status = 'CURRENT' where countryNumber='Germany';
update Country set status = 'CURRENT' where countryNumber='Ghana';
update Country set status = 'CURRENT' where countryNumber='Gibraltar';
update Country set status = 'CURRENT' where countryNumber='Greece';
update Country set status = 'CURRENT' where countryNumber='Greenland';
update Country set status = 'CURRENT' where countryNumber='Grenada';
update Country set status = 'CURRENT' where countryNumber='Guadeloupe';
update Country set status = 'CURRENT' where countryNumber='Guam';
update Country set status = 'CURRENT' where countryNumber='Guatemala';
update Country set status = 'CURRENT' where countryNumber='Guernsey';
update Country set status = 'CURRENT' where countryNumber='Guinea';
update Country set status = 'CURRENT' where countryNumber='Guinea-Bissau';
update Country set status = 'CURRENT' where countryNumber='Guyana';
update Country set status = 'CURRENT' where countryNumber='Haiti';
update Country set status = 'CURRENT' where countryNumber='Heard Island And Mcdonald Islands';
update Country set status = 'CURRENT' where countryNumber='Holy See (Vatican City State)';
update Country set status = 'CURRENT' where countryNumber='Honduras';
update Country set status = 'CURRENT' where countryNumber='Hong Kong';
update Country set status = 'CURRENT' where countryNumber='Hungary';
update Country set status = 'CURRENT' where countryNumber='Iceland';
update Country set status = 'CURRENT' where countryNumber='India';
update Country set status = 'CURRENT' where countryNumber='Indonesia';
update Country set status = 'CURRENT' where countryNumber='Iran, Islamic Republic Of';
update Country set status = 'CURRENT' where countryNumber='Iraq';
update Country set status = 'CURRENT' where countryNumber='Ireland';
update Country set status = 'CURRENT' where countryNumber='Isle of Man';
update Country set status = 'CURRENT' where countryNumber='Israel';
update Country set status = 'CURRENT' where countryNumber='Italy';
update Country set status = 'CURRENT' where countryNumber='Jamaica';
update Country set status = 'CURRENT' where countryNumber='Japan';
update Country set status = 'CURRENT' where countryNumber='Jersey';
update Country set status = 'CURRENT' where countryNumber='Jordan';
update Country set status = 'CURRENT' where countryNumber='Kazakhstan';
update Country set status = 'CURRENT' where countryNumber='Kenya';
update Country set status = 'CURRENT' where countryNumber='Kiribati';
update Country set status = 'CURRENT' where countryNumber='Korea, Democratic People''s Republic Of';
update Country set status = 'CURRENT' where countryNumber='Korea, Republic Of';
update Country set status = 'CURRENT' where countryNumber='Kuwait';
update Country set status = 'CURRENT' where countryNumber='Kyrgyzstan';
update Country set status = 'CURRENT' where countryNumber='Lao People''s Democratic Republic';
update Country set status = 'CURRENT' where countryNumber='Latvia';
update Country set status = 'CURRENT' where countryNumber='Lebanon';
update Country set status = 'CURRENT' where countryNumber='Lesotho';
update Country set status = 'CURRENT' where countryNumber='Liberia';
update Country set status = 'CURRENT' where countryNumber='Libya';
update Country set status = 'CURRENT' where countryNumber='Liechtenstein';
update Country set status = 'CURRENT' where countryNumber='Lithuania';
update Country set status = 'CURRENT' where countryNumber='Luxembourg';
update Country set status = 'CURRENT' where countryNumber='Macao';
update Country set status = 'CURRENT' where countryNumber='Macedonia, The Former Yugoslav Republic of';
update Country set status = 'CURRENT' where countryNumber='Madagascar';
update Country set status = 'CURRENT' where countryNumber='Malawi';
update Country set status = 'CURRENT' where countryNumber='Malaysia';
update Country set status = 'CURRENT' where countryNumber='Maldives';
update Country set status = 'CURRENT' where countryNumber='Mali';
update Country set status = 'CURRENT' where countryNumber='Malta';
update Country set status = 'CURRENT' where countryNumber='Marshall Islands';
update Country set status = 'CURRENT' where countryNumber='Martinique';
update Country set status = 'CURRENT' where countryNumber='Mauritania';
update Country set status = 'CURRENT' where countryNumber='Mauritius';
update Country set status = 'CURRENT' where countryNumber='Mayotte';
update Country set status = 'CURRENT' where countryNumber='Mexico';
update Country set status = 'CURRENT' where countryNumber='Micronesia, Federated States Of';
update Country set status = 'CURRENT' where countryNumber='Moldova, Republic Of';
update Country set status = 'CURRENT' where countryNumber='Monaco';
update Country set status = 'CURRENT' where countryNumber='Mongolia';
update Country set status = 'CURRENT' where countryNumber='Montenegro';
update Country set status = 'CURRENT' where countryNumber='Montserrat';
update Country set status = 'CURRENT' where countryNumber='Morocco';
update Country set status = 'CURRENT' where countryNumber='Mozambique';
update Country set status = 'CURRENT' where countryNumber='Myanmar';
update Country set status = 'CURRENT' where countryNumber='Namibia';
update Country set status = 'CURRENT' where countryNumber='Nauru';
update Country set status = 'CURRENT' where countryNumber='Nepal';
update Country set status = 'CURRENT' where countryNumber='Netherlands';
update Country set status = 'CURRENT' where countryNumber='New Caledonia';
update Country set status = 'CURRENT' where countryNumber='New Zealand';
update Country set status = 'CURRENT' where countryNumber='Nicaragua';
update Country set status = 'CURRENT' where countryNumber='Niger';
update Country set status = 'CURRENT' where countryNumber='Nigeria';
update Country set status = 'CURRENT' where countryNumber='Niue';
update Country set status = 'CURRENT' where countryNumber='Norfolk Island';
update Country set status = 'CURRENT' where countryNumber='Northern Mariana Islands';
update Country set status = 'CURRENT' where countryNumber='Norway';
update Country set status = 'CURRENT' where countryNumber='Oman';
update Country set status = 'CURRENT' where countryNumber='Pakistan';
update Country set status = 'CURRENT' where countryNumber='Palau';
update Country set status = 'CURRENT' where countryNumber='Palestine, State of';
update Country set status = 'CURRENT' where countryNumber='Panama';
update Country set status = 'CURRENT' where countryNumber='Papua New Guinea';
update Country set status = 'CURRENT' where countryNumber='Paraguay';
update Country set status = 'CURRENT' where countryNumber='Peru';
update Country set status = 'CURRENT' where countryNumber='Philippines';
update Country set status = 'CURRENT' where countryNumber='Pitcairn';
update Country set status = 'CURRENT' where countryNumber='Poland';
update Country set status = 'CURRENT' where countryNumber='Portugal';
update Country set status = 'CURRENT' where countryNumber='Puerto Rico';
update Country set status = 'CURRENT' where countryNumber='Qatar';
update Country set status = 'CURRENT' where countryNumber='Reunion';
update Country set status = 'CURRENT' where countryNumber='Romania';
update Country set status = 'CURRENT' where countryNumber='Russian Federation';
update Country set status = 'CURRENT' where countryNumber='Rwanda';
update Country set status = 'CURRENT' where countryNumber='Saint Barthelemy';
update Country set status = 'CURRENT' where countryNumber='Saint Helena, Ascension And Tristan Da Cunha';
update Country set status = 'CURRENT' where countryNumber='Saint Kitts And Nevis';
update Country set status = 'CURRENT' where countryNumber='Saint Lucia';
update Country set status = 'CURRENT' where countryNumber='Saint Martin (French Part)';
update Country set status = 'CURRENT' where countryNumber='Saint Pierre And Miquelon';
update Country set status = 'CURRENT' where countryNumber='Saint Vincent And The Grenadines';
update Country set status = 'CURRENT' where countryNumber='Samoa';
update Country set status = 'CURRENT' where countryNumber='San Marino';
update Country set status = 'CURRENT' where countryNumber='Sao Tome And Principe';
update Country set status = 'CURRENT' where countryNumber='Saudi Arabia';
update Country set status = 'CURRENT' where countryNumber='Senegal';
update Country set status = 'CURRENT' where countryNumber='Serbia';
update Country set status = 'CURRENT' where countryNumber='Seychelles';
update Country set status = 'CURRENT' where countryNumber='Sierra Leone';
update Country set status = 'CURRENT' where countryNumber='Singapore';
update Country set status = 'CURRENT' where countryNumber='Sint Maarten (Dutch Part)';
update Country set status = 'CURRENT' where countryNumber='Slovakia';
update Country set status = 'CURRENT' where countryNumber='Slovenia';
update Country set status = 'CURRENT' where countryNumber='Solomon Islands';
update Country set status = 'CURRENT' where countryNumber='Somalia';
update Country set status = 'CURRENT' where countryNumber='South Africa';
update Country set status = 'CURRENT' where countryNumber='South Georgia and the South Sandwich Islands';
update Country set status = 'CURRENT' where countryNumber='South Sudan';
update Country set status = 'CURRENT' where countryNumber='Spain';
update Country set status = 'CURRENT' where countryNumber='Sri Lanka';
update Country set status = 'CURRENT' where countryNumber='Sudan';
update Country set status = 'CURRENT' where countryNumber='Suriname';
update Country set status = 'CURRENT' where countryNumber='Svalbard And Jan Mayen';
update Country set status = 'CURRENT' where countryNumber='Swaziland';
update Country set status = 'CURRENT' where countryNumber='Sweden';
update Country set status = 'CURRENT' where countryNumber='Switzerland';
update Country set status = 'CURRENT' where countryNumber='Syrian Arab Republic';
update Country set status = 'CURRENT' where countryNumber='Taiwan, Province Of China';
update Country set status = 'CURRENT' where countryNumber='Tajikistan';
update Country set status = 'CURRENT' where countryNumber='Tanzania, United Republic Of';
update Country set status = 'CURRENT' where countryNumber='Thailand';
update Country set status = 'CURRENT' where countryNumber='Timor-Leste';
update Country set status = 'CURRENT' where countryNumber='Togo';
update Country set status = 'CURRENT' where countryNumber='Tokelau';
update Country set status = 'CURRENT' where countryNumber='Tonga';
update Country set status = 'CURRENT' where countryNumber='Trinidad And Tobago';
update Country set status = 'CURRENT' where countryNumber='Tunisia';
update Country set status = 'CURRENT' where countryNumber='Turkey';
update Country set status = 'CURRENT' where countryNumber='Turkmenistan';
update Country set status = 'CURRENT' where countryNumber='Turks And Caicos Islands';
update Country set status = 'CURRENT' where countryNumber='Tuvalu';
update Country set status = 'CURRENT' where countryNumber='Uganda';
update Country set status = 'CURRENT' where countryNumber='Ukraine';
update Country set status = 'CURRENT' where countryNumber='United Arab Emirates';
update Country set status = 'CURRENT' where countryNumber='United Kingdom';
update Country set status = 'CURRENT' where countryNumber='United States';
update Country set status = 'CURRENT' where countryNumber='United States Minor Outlying Islands';
update Country set status = 'CURRENT' where countryNumber='Uruguay';
update Country set status = 'CURRENT' where countryNumber='Uzbekistan';
update Country set status = 'CURRENT' where countryNumber='Vanuatu';
update Country set status = 'CURRENT' where countryNumber='Venezuela, Bolivarian Republic Of';
update Country set status = 'CURRENT' where countryNumber='Vietnam';
update Country set status = 'CURRENT' where countryNumber='Virgin Islands, British';
update Country set status = 'CURRENT' where countryNumber='Virgin Islands, U.S.';
update Country set status = 'CURRENT' where countryNumber='Wallis And Futuna';
update Country set status = 'CURRENT' where countryNumber='Western Sahara';
update Country set status = 'CURRENT' where countryNumber='Yemen';
update Country set status = 'CURRENT' where countryNumber='Zambia';
update Country set status = 'CURRENT' where countryNumber='Zimbabwe';
