-- YOU MUST RUN THE ETL AFTER THIS RELEASE FOR STEPS GRADE, SITE, TRUST

TRUNCATE TABLE `Site`;
TRUNCATE TABLE `Grade`;
TRUNCATE TABLE `Trust`;

ALTER TABLE `Site`
DROP PRIMARY KEY;

ALTER TABLE `Site`
DROP index `siteCode`;

ALTER TABLE `Site`
ADD COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE `Site`
MODIFY `siteCode` VARCHAR(255);

--make trust code nullable
ALTER TABLE `Site`
MODIFY `trustCode` VARCHAR(255);

ALTER TABLE `Site`
ADD COLUMN `trustId` bigint(20);

---

ALTER TABLE `Trust`
DROP PRIMARY KEY;

ALTER TABLE `Trust`
DROP index `code`;

ALTER TABLE `Trust`
ADD COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE `Trust`
MODIFY `code` VARCHAR(255);

---

ALTER TABLE `Grade`
DROP PRIMARY KEY;

ALTER TABLE `Grade`
DROP index `abbreviation`;

ALTER TABLE `Grade`
ADD COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE `Grade`
MODIFY `abbreviation` VARCHAR(255);

ALTER TABLE `Grade`
ADD COLUMN `intrepidId` VARCHAR(255);

---

ALTER TABLE `MedicalSchool`
DROP index `code`;

ALTER TABLE `MedicalSchool`
MODIFY `code` VARCHAR(255);