ALTER TABLE `Site`
DROP PRIMARY KEY;

ALTER TABLE `Site`
DROP index `siteCode`;

ALTER TABLE `Site`
ADD COLUMN `id` bigint(10) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE `Site`
MODIFY `siteCode` VARCHAR(255);

---

ALTER TABLE `Trust`
DROP PRIMARY KEY;

ALTER TABLE `Trust`
DROP index `code`;

ALTER TABLE `Trust`
ADD COLUMN `id` bigint(10) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE `Trust`
MODIFY `code` VARCHAR(255);

---

ALTER TABLE `Grade`
DROP PRIMARY KEY;

ALTER TABLE `Grade`
DROP index `abbreviation`;

ALTER TABLE `Grade`
ADD COLUMN `id` bigint(10) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE `Grade`
MODIFY `abbreviation` VARCHAR(255);

ALTER TABLE `Grade`
ADD COLUMN `intrepidId` VARCHAR(255);